### ISSUE TITLE
Rename cardinality N/A to consistent NO_RESULT

### ISSUE THREAD

**Issue by tailhook** [edgedb/edgedb#1024]
Got this unclear error `cardinality N/A cannot be requested`. Also it looks like there are few other instances in `edgecon.pyx`. Should everywhere be NO_RESULT as we document in RST files.

**Comment by tailhook** [comment]
@aeros, you can take this one, if you're still looking for a trivial task.

**Comment by aeros** [comment]
Thanks, I'd be willing to help with this.

**Comment by tailhook** [comment]
@aeros, what's your status? Is the issue description clear enough (well, I've written it just as a note to myself, so it's not detailed enough)? Any help needed?

**Comment by aeros** [comment]
@tailhook I was out of town when I responded to the @ mention, I just got back home earlier today. I'll have time to work on it this week and will let you know if I have any questions. Thanks for checking (:

**Comment by aeros** [comment]
@tailhook I was doing a bit of investigation into this to determine all of the different areas where the cardinality result should be changed from `NOT_APPLICABLE` to `NO_RESULT`.

I believe the primary area to change is here: https://github.com/edgedb/edgedb/blob/570375f163d08e132b98e8b78f62f2105710aff5/edb/server/compiler/enums.py#L42-L46
and everything that currently references `NOT_APPLICABLE`; as well as changing:

https://github.com/edgedb/edgedb/blob/570375f163d08e132b98e8b78f62f2105710aff5/edb/server/mng_port/edgecon.pyx#L749-L756

to return `CARD_NO_RESULT` or `CARD_NONE` instead of raising the `BinaryProtocolError` (which would be an alias to `ResultCardinality.NO_RESULT`, similar to the above `CARD_ONE` and `CARD_MANY`). 

Alternatively, did you simply mean to change the text of the error message from `cardinality N/A cannot be requested` to `cardinality NO_RESULT cannot be requested`? 

The scope of this issue isn't 100% clear to me, since you mentioned "Should everywhere be NO_RESULT as we document in RST files", but the first sentence seemed to indicate that this issue is primarily based around the error message.

**Comment by tailhook** [comment]
Yes, I meant both `ResultCardinality` and the error message.

But I'm not sure why we might want to turn an exception to return value. We don't accept cardinality of NO_RESULT from a client, we can only return it in `Describe` message. So exception is fine here, just need to refer to the cardinality consistently.

**Comment by aeros** [comment]
> Yes, I meant both ResultCardinality and the error message.

Okay, thanks for clarifying.

> But I'm not sure why we might want to turn an exception to return value. We don't accept cardinality of NO_RESULT from a client, we can only return it in Describe message. So exception is fine here, just need to have a consistent title for this variant everywhere.

Ah, that makes sense. I'm not very familiar with the logic in `edgecon.pyx`, this is actually my first time looking at that directory (`edb/server/mng_port/`). The purpose behind the exception wasn't entirely clear to me when I wrote the above comment.

**Comment by tailhook** [comment]
@aeros you can probably take #1016 if you want another issue. It's a bit more complex and requires a test, but it should also be more fun to do.

**Comment by aeros** [comment]
No problem. I can't guarantee when I'll have time to work on it since I'm wrapped up in a few other projects and obligations at the moment, but if there's not an imminent deadline on #1016 I'd be glad to work on it when I do get the chance.
