### ISSUE TITLE
Subcommands in edgedb-repl

### ISSUE THREAD

**Issue by tailhook** [edgedb/edgedb#1029]
# Backround

Currently, they look like:
```
edgedb create role <rolename>
edgedb create datbase <dbname>
```
And help looks like:
```
> edgedb --help
Usage: edgedb [OPTIONS] COMMAND [ARGS]...

Options:
  -h, --host TEXT
  -p, --port INTEGER
  -u, --user TEXT
  -d, --database TEXT
  --admin
  --password / --no-password
  --password-from-stdin
  -?, --help                  Show this message and exit.

Commands:
  alter
  configure
  create
  drop
> edgedb create --help
Usage: edgedb create [OPTIONS] COMMAND [ARGS]...

Options:
  -h, --host TEXT
  -p, --port INTEGER
  -u, --user TEXT
  -d, --database TEXT
  --admin
  --password / --no-password
  --password-from-stdin
  -?, --help                  Show this message and exit.

Commands:
  role

```

# Proposal

What I would like to have:
```
edgedb create-role <rolename>
edgedb create-datbase <dbname>
```
And help like this:
```
> edgedb --help
Usage: edgedb [OPTIONS] COMMAND [ARGS]...

Options:
  -h, --host TEXT
  -p, --port INTEGER
  -u, --user TEXT
  -d, --database TEXT
  --admin
  --password / --no-password
  --password-from-stdin
  -?, --help                  Show this message and exit.

Commands:
  alter-role
  configure-role
  create-role
  create-database
  drop-role
```

**Comment by 1st1** [comment]
I also have a couple of reservations about the current cli design, but Elvis managed to convince me that it's better than the alternatives. Let's quickly reiterate all options with their cons/pros:

-------

**Current Design**

```
edgedb create role <name>
edgedb create database <name>
```

Pros: 

* Mimics EdgeQL syntax. This is a good feature since once you know either the cli or EdgeQL you can learn the other one faster.

Cons:

* Hides **what** can be created/altered/configured. You need to run `edgedb create --help` to see the full list of what can be created via cli.

* "edgedb create" isn't a valid command, it can only display help message. "edgedb create role" is the actual command.

-------

**Paul's proposal**

```
edgedb create-role <name>
edgedb create-datbase <name>
```

Pros:

* `--help` lists all commands at once so it's immediately clear to the user what functionality the cli provides.

* Like the current design, the cli naming/order replicates EdgeQL.

Cons:

* `--help` list **all** commands **at once** so the user will see a very long list of them. For every logical entity there will be at least three commands, e.g.: `create-role`, `alter-role`, `drop-role`.

-------

**Third option**

```
edgedb role create <name>
edgedb datbase create <name>
```

The help would look like this:

```
> edgedb --help
Usage: edgedb [OPTIONS] COMMAND [ARGS]...

Options:
  -h, --host TEXT
  -p, --port INTEGER
  -u, --user TEXT
  -d, --database TEXT
  --admin
  --password / --no-password
  --password-from-stdin
  -?, --help                  Show this message and exit.

Commands:
  role
  database
```

Pros:

* `--help` lists all "entities" at once, i.e. the user will understand that `edgedb` can do something with roles, databases, etc.

Cons:

* The order of subcommands is different from EdgeQL.

-------

I'd also like to point out that we can simply keep the status quo and just tweak the `--help` message to list subcommands as follows:

```
edgedb create role <name>
edgedb create datbase <name>
```

**Comment by tailhook** [comment]
> I'd also like to point out that we can simply keep the status quo and just tweak the --help message to list subcommands as follows:

But we can't make completiion work:
```
$ edgedb <tab>
create -- create something (what would you write here?)
```
(And yes, completion and help is **generated** by [`clap`](https://crates.io/crates/clap) so if we deviate a lot of what is done there, we're going to support fork of it or maintain all those builtin things by ourselves for no reason).

> Mimics EdgeQL syntax.

It's still far from the edgeql syntax:
```
create role xxx --password --allow-login
```
In these cases where the syntax is close but not exactly the same, it's often syntax that's farther is better because is more memorable.

**Comment by tailhook** [comment]
By the way, if we "mimic EdgeQL syntax" on the command-line, how would we make list roles and configuration data?

As far as I can see in #1021 we use `SELECT` for that. I don't think that:
```
edgedb select cfg::Config.auth --priority --method 
```
.. makes any sense, whereas both:
```
edgedb list-roles
edgedb role list
```
Are good enough.
*(I know it's not the same, but don't know roles listing syntax off the top of my head)*

**Comment by tailhook** [comment]
On friday meeting we agreed to use the dashed form of commands as was in the original proposal.
