### ISSUE TITLE
InternalServerError error creating scalar type

### ISSUE THREAD

**Issue by Fogapod** [edgedb/edgedb#1182]
- EdgeDB Version: `1.0-alpha.2+dev.505.g5b68ec24`

Steps to Reproduce:

```
START TRANSACTION;
CREATE MIGRATION init TO {
    module default {
        scalar type unique_name extending str {
            constraint exclusive;
        }
    }
};
COMMIT MIGRATION init;
```
Error: `InternalServerError: column "78096142-4760-11ea-ad7d-c3dbbf5ced49" does not exist`

I found another InternalServerError while playing with this:
```
START TRANSACTION;
CREATE MIGRATION init TO {
    module default {
        scalar type unique_name extending str {
            constraint exclusive on (str_lower(__subject__));
        }
    }
};
COMMIT MIGRATION init;
```
Error: `InternalServerError: argument of CHECK must be type boolean, not type text`

I'm not sure if the latter is a bug, I'm using it wrong, but `InternalServerError` is scary.

Is it possible to declare `exclusive` constraint in scalar so that it checks lowercase value?
My plan to use it is:
```
type User {
    required property nickname -> unique_name;
    # ...
    index on (str_lower(__subject__.nickname));
}
```
`unique_name` has other constraints, but I removed them to simplify my report.

**Comment by elprans** [comment]
Ah. Right. `exclusive` constraints are not supported on scalar types. The bug is that there's no explicit check for that.  

You can only declare constraints on links and properties (support for object types is being added), so:

```
type User {
    required property nickname -> str {
        constraint exclusive on (str_lower(__subject__));
    }
}
```

You don't need a separate index for the property, since the constraint would normally generate an implicit unique index.

**Comment by elprans** [comment]
@vpetrovykh, please look into adding an explicit check, prohibiting exclusive constraints on scalars.  I'm thinking this should be done by marking a constraint as an "aggregate" constraint, i.e. a `set of` function.

**Comment by vpetrovykh** [comment]
"Aggregate" constraint sounds interesting, but the issue here is that any constraint that refers to the pointer source will have issues when applied to a scalar type, regardless of whether it's aggregate or not. Incidentally, is it possible to make a constraint referring to a link property and the link target? Because that type of constraint could not be applied to a scalar either.

To make a more concrete example, consider this:
```
type Foo {
  proeprty val -> int64;
}

type Bar {
  link foo -> Foo {
    property mult -> int64;
  }
}
```
The question is whether I can create a constraint on link `foo` that says that the link target's `val` must be divisible by `mult`? 

So it looks to me that there are constraints that apply to scalars (which can be used on scalar types or properties) and constraints that apply to pointers (which can only apply to links and properties). Whether they are aggregate or not is an orthogonal parameter here.

**Comment by elprans** [comment]
> The question is whether I can create a constraint on link `foo` that says that the link target's `val` must be divisible by `mult`?

Going "up" like this is not supported for all pointer constraints regardless of whether they're scalar or not.  If you need to define a constraint on multiple properties or links, you must use an `object type` level constraint.

> "Aggregate" constraint sounds interesting, but the issue here is that any constraint that refers to the pointer source will have issues when applied to a scalar type

> Whether they are aggregate or not is an orthogonal parameter here.

No. The original report had an `exclusive` constraint defined on  `scalar type` *definition*.  It's perfectly fine to declare `exclusive` on a scalar *property*, though.

This is invalid:

```
        scalar type unique_name extending str {
            constraint exclusive;
        }
```

This is valid:

```
        type Foo {
            link name -> unique_name {
                constraint exclusive;
            }
        }
```

**Comment by vpetrovykh** [comment]
To summarize a slack discussion, it appears that a more reasonable flag name is "pointer-only" (maybe just "pointer") rather than "aggregate". The reasoning is as follows:
- `exclusive` constraint can only be applied to pointers.
- One could interpret `exclusive` constraint applied to an object type to be a NOP, because all objects are already unique. However, currently we forbid applying this constraint to object types (it's illegal to do `type Foo {constraint exclusive}`).

Basically if we forbid the `exclusive` constraint for scalar type definitions and object type definitions, then it's more appropriate to label it "pointer-only". On the other hand, if we allow it to appear on object types (even though it has no effect), then it would make sense to label it as "aggregate" and use that as the feature that makes it illegal for scalar types.

Proposed syntax (for internal usage only, so valid only during EdgeDB initialization):
```
CREATE ABSTRACT CONSTRAINT
std::exclusive EXTENDING std::constraint
{
    SET is_pointer_only := true;
    SET errmessage := '{__subject__} violates exclusivity constraint';
    USING (std::_is_exclusive(__subject__));
};
```

**Comment by elprans** [comment]
Object-level constraints are coming (see #1164), so `is_aggregate` would be a more appropriate flag here.
