### ISSUE TITLE
repl history/editing

### ISSUE THREAD

**Issue by 1st1** [edgedb/edgedb#1247]
Since we won't likely to have a fully functioning VIM mode in the new rusty repl, I propose to add the following repl commands to mitigate that:

`\e [N]` or `\edit [N]` to open the system `$EDITOR` for the last (if `N` isn't provided), or the last N-th (if `N` is negative), or the N-th (if `N` is positive) command.

`\s` or `\history` to open a pager with the history of executed commands (latest to oldest), e.g.

```
[43]
    SELECT User {
        name
    };

[42]
   SELECT 1 / 0;
```

The user then can press `[ESC]`, enter `\e 42` and edit the `SELECT 1 / 0` query.

**Comment by elprans** [comment]
psql users `\s` for history shortcut

**Comment by 1st1** [comment]
> psql uses \s for history shortcut

Works for us, I think.

**Comment by tailhook** [comment]
Well, why we need a command if that's rather better be made a shortcut, like `F2` or `Ctrl+O` or something? I.e. if in the middle of the request you realized that it's hard to edit this query it's bad idea to execute query (to have it added to the history) and then edit it.

Well, currently we can't make the shortcut because rustyline doesn't allow custom commands, but I think this can be fixed.

**Comment by 1st1** [comment]
> Why we need a command if that's rather better be made a shortcut, like F2 or Ctrl+O or something?

Can we have both?

**Comment by tailhook** [comment]
First version of the commands is implemented. They currently only support negative numbers, because that allows seamless integration with history. (I.e. with positive numbers it's unclear whether `1` is a first item in current session or the first history entry, both options have their downsides).

Let me know if that doesn't work for you.
