### ISSUE TITLE
Require 'required' or 'optional' modifier for properties and links

### ISSUE THREAD

**Issue by 1st1** [edgedb/edgedb#1342]

**Comment by 1st1** [comment]
@vpetrovykh @ambv we need to tackle this ASAP.

**Comment by ambv** [comment]
I'm on this right now.

**Comment by ambv** [comment]
Current status: making tests run after the change. Since the unit tests pre-run a large script with all schemas, essentially the change needs to be perfect for tests to even start. Getting there.

At the moment I left the default non-qualified CREATE PROPERTY and CREATE LINK in DDL so that dump/restore with Alpha 2 works. The syntax error is raised later when the pointer is created in schema/pointers.py.

However, I thought that since SDL is not part of dump/restore, we can just drop the relevant productions from edb/edgeql/parser/grammar/sdl.py and the current change does that. Sadly, when somebody when tries to use an unqualified property declaration, the syntax error is rather awful. For example for `property seq_prop -> seq_t` the error just says: `"Unexpected 'seq_prop'"`.

So I will reinstate the non-qualified property and link productions so that the syntax error is nicer. Since this will be already annoying to users, we need to make sure that we at least aren't criminally annoying :-)

**Comment by 1st1** [comment]
> For example for property seq_prop -> seq_t the error just says: "Unexpected 'seq_prop'".

You solve that by actually implementing that production and making it raise a nice error suggesting to put either OPTIONAL or REQUIRED qualifier.

**Comment by 1st1** [comment]
Here's an example of us raising a nice error when somebody uses `$` to prefix function parameters: https://github.com/edgedb/edgedb/blob/b8d1307cc6e806bd1c6ccd4ad5fbd9f83152cca4/edb/edgeql/parser/grammar/commondl.py#L182-L191
