### ISSUE TITLE
Add __tname__ object magic field & session config to enable it

### ISSUE THREAD

**Issue by 1st1** [edgedb/edgedb#1350]
For REPL & the tutorial it's a great UX to display type names when we render results. Introspecting schema is a suboptimal solution as it's slow and not always practical to do.

**Comment by tailhook** [comment]
I also think that we may want to configure all implicit fields rather than just `__tname__`. I.e. `__tid__` is not used in repl now, unless you enable `introspect-types` which should rely on the new `__tname__` instead. And `id` is also not needed anywhere except repl (for empty shapes).

I'm not sure this should be a session config, rather than per-request config, like we do `implicit_limit` though (I'd like to disable it for statically typed queries like `list-databases` in CLI).

**Comment by fmoor** [comment]
Also, I don't think clients for statically typed languages like go will have much use for __tid__, __tname__ etc. since query results  will be marshaled into user defined types.

**Comment by elprans** [comment]
@1st1 is this done?

**Comment by 1st1** [comment]
I think so
