### ISSUE TITLE
InternalServerError: cannot alter type

### ISSUE THREAD

**Issue by nkhitrov** [edgedb/edgedb#1370]
- EdgeDB Version: EdgeDB 1.0-alpha.2+g16f75ece5.d20200122
- OS Version: Windos 10 Educational, Version: 1909, Build: 18363.778

Steps to Reproduce:
```
START TRANSACTION;
CREATE MIGRATION m2 TO {
    module default {
        type User {
            required property scopes -> array<scope>;
        }
        scalar type scope extending str {
            constraint one_of (
                '1', '2'
            );
        }
    }
};
COMMIT MIGRATION m2;
COMMIT;
```

Error log:
```
InternalServerError: cannot alter type ""edgedb_e1d3ab02-7c59-11ea-9cc7-f7e49d2fb386"."87c9d94a-87f0-11ea-b4ba-db2bb9dbfd2b_domain"" because column "6716f2a1-87ef-11ea-bb56-fd1198a88276.scopes" uses it
```

May be related to this issue #1369.

**Comment by 1st1** [comment]
Can you also provide us with the initial state of the schema on which this migration fails?

**Comment by nsidnev** [comment]
We just bootstrapped the new EdgeDB server (version - `1.0-alpha.3+dev.163.gad37ad85.d20200426`) with `edb server --temp-dir` and applied this migration.

**Comment by elprans** [comment]
Yes, this is due to a Postgres limitation.  It disallows altering domain types if they're used in an array or a composite type.  As a workaround for now, try reordering the definitions in the schema, placing `scope` first.

**Comment by nsidnev** [comment]
Just tried this on a clean instance, but it failed with the same error. We'll probably write the `Scope` type instaed of the scalar type as a workaround.

**Comment by Slyfoxy** [comment]
Hi, @elprans ! Thank you for your help. Unfortunately, this method did not work. The same error happens. 😢

**Comment by elprans** [comment]
Right, so then the only way around is to use DDL commands directly (and in correct order):

```
create scalar type scope extending str {
    create constraint one_of ('1', '2');
};

create type User {
    create required property scopes -> array<scope>;
};

```

**Comment by 1st1** [comment]
@elprans Can we fix this for alpha 3? If not please move to alpha 4.

**Comment by elprans** [comment]
Because this is a Postgres limitation the fix would likely be fairly involved, moving.

**Comment by msullivan** [comment]
This particular manifestation of the issue should be easy to fix: because of the vagaries of the priority system, pgsql/delta.py just happens to be creating the constraint late, in a way that puts it after the table and column are created.

The trickier thing is when we need to do a bona-fide alter that adds a constraint. I think the approach is going to have to be:
1. Alter all of the columns that use the type as part of a composite to use an equivalent type. This could require creating temporary tuple types.
2. Add the constraint to the domain
3. Alter all the columns back. Delete any temporary types.

That is nasty, but definitely doable.
