### ISSUE TITLE
Implement traits

### ISSUE THREAD

**Issue by 1st1** [edgedb/edgedb#1466]
We need a mechanism to allow overriding functions like `std::str` for user-defined types and in extensions. One of the ways to implement this would be to introduce a concept of "traits":

```
CREATE TRAIT std::to_str(o: MyType) -> str { ... }
```

Traits can be specialized functions implementing single-dispatch for their first argument.

See also https://github.com/edgedb/edgedb/issues/1439 for more context.

**Comment by dmgolembiowski** [comment]
I have been wondering what a trait-based system in EdgeDB would look like for some time now. It's been entertaining to dream-up their design. Associated types seem especially tricky to verify -- and since having a semblance of strongly-typed data seems important when you're dealing with an actual database -- which makes me wonder if the encoding of the data itself can be leveraged to build a trait system. 
The inspiration for this idea comes from a late-night 3blue1brown binge-watching session, where the video's producer discusses Hamming Codes in a way I hadn't seen before: https://www.youtube.com/watch?v=b3NxrZOu_CE&t=390

**Comment by msullivan** [comment]
We already have function overloading. I don't know if there anything else we're planning here?
