### ISSUE TITLE
edgedb restore does not restore databases

### ISSUE THREAD

**Issue by Fogapod** [edgedb/edgedb#1485]
- EdgeDB Version: `1.0.0-alpha.3+gfc28c7156.d20200612`
- OS Version:

### Summary
Recently I had to use `edgedb restore` and it didnt restore my databases.
The only restored database was `edgedb` as it is always present.
To fix this you have to create databases before using `edgedb restore`.

Seems like the same is true for users.

### Steps to Reproduce
1. init edgedb
2. create new database (`CREATE DATABASE`)
3. use `edgedb dump`
4. use `edgedb restore` on fresh edgedb instance

### Schema
```edgeql
CREATE DATABASE test;
```

**Comment by elprans** [comment]
This is by design. `edgedb dump` and `edgedb restore` restore the *contents* of a database, but not the databases themselves or any other global objects like roles.  Essentially, they're equivalents of `pg_dump` and `pg_restore` in Postgres.  What *is* lacking currently is an equivalent of `pg_dumpall` which dumps the entire instance.

**Comment by Fogapod** [comment]
Being able do restore everything would be very useful since breaking changes are still frequent

**Comment by elprans** [comment]
The [RFC 1001](https://github.com/edgedb/rfcs/blob/master/text/1001-edgedb-server-control.rst) (in particular https://github.com/edgedb/edgedb-cli/issues/80) is going to land in the `edgedb-cli` very soon, which will turn installation and instance upgrades into a single command.
