### ISSUE TITLE
Bug in interaction of OPTIONAL and SET OF

### ISSUE THREAD

**Issue by vpetrovykh** [edgedb/edgedb#1640]
- EdgeDB Version: 1.0-alpha.4+dev.92.g20b0bd7f
- OS Version: Linux

Steps to Reproduce:

```
victor> CREATE TYPE Foo;
OK: CREATE
victor> SELECT (<str>Foo.id) ?? (<str>count(Foo));
{}
```
The expected result is `{'0'}`, since we expect the `count` of an empty set be called.

**Comment by msullivan** [comment]
Another example is `SELECT (<str>Foo.id ?= <str>count(Foo));`, which returns `{}` instead of `{false}`.

There seems to be some trickiness, here, though, since we *do* want those sides to be correlated. If we add a `num` field to `Foo`, we want `SELECT (Foo.num ?= count(Foo));` to only be true for objects where num = 1, I think.

**Comment by elprans** [comment]
> since we _do_ want those sides to be correlated. If we add a `num` field to `Foo`, we want `SELECT (Foo.num ?= count(Foo));` to only be true for objects where num = 1,

That's correct.

**Comment by msullivan** [comment]
A related issue, albeit in the other direction, that probably needs to be tackled together with this:
```
sully> SELECT (Foo ?= Foo, Foo);
{(true, Object {id: {}})}
```
