### ISSUE TITLE
Prohibit DML queries in function bodies 

### ISSUE THREAD

**Issue by vpetrovykh** [edgedb/edgedb#1661]
The proposal is to prohibit `INSERT`, `UPDATE`, and `DELETE` statements in function bodies.

Currently these statements cannot appear in conditional expressions. More specifically, they are executed unconditionally, so it is semantically misleading to place them in a conditional branch that may or may not be executed - so this is forbidden. There's a specialized form of these statements that allows them to be conditionally executed #1639.

However, functions don't have the same unconditional execution policy and if these statements were to appear in functions, this could lead to unpredictable results, especially since function calls may be optimized by the query planner based on volatility and where they appear. In order to prevent unspecified behavior we currently choose to ban data manipulation inside function bodies.

**Comment by Fogapod** [comment]
Does this include `DELETE` statement?

**Comment by elprans** [comment]
> Does this include `DELETE` statement?

Yes.

To clarify, the decision to prohibit DML in functions plugs an undefined behavior hole until we figure out how to allow this safely.

**Comment by vpetrovykh** [comment]
I've updated the top post to include `DELETE` there as well.

**Comment by Fogapod** [comment]
I hope you understand that this would be a big breaking change. Is there is absolutely no other way around at the moment?
The ability to use DDL in functions was there for months and several alphas (if not from 1st alpha?).
Some people already integrated it (including myself):
- https://spectrum.chat/edgedb/general/personal-accomplishment-edgedb-authentication-from-svelte-js~ff16a60c-91b2-4e85-aa13-1aa3d22d9500

**Comment by elprans** [comment]
> I hope you understand that this would be a big breaking change.

Absolutely!  Hence the "under discussion" label here.

> The ability to use DML in functions was there for months

You might have noticed that functions with DML have serious issues: 1) it's impossible to see the effect of a data-modifying function in a calling query;  2) depending on where the call site in the query is, the function might not even get called, or it might, the behavior is undefined.  We'd like to avoid inheriting PostgreSQL mistakes and it's not too late yet.

> Is there is absolutely no other way around at the moment?

We can add a configuration knob that enables the current behavior, e.g. `CONFIGURE SYSTEM/SESSION SET allow_dml_in_functions := true` (it'll be disabled by default).

Furhter, we will look into finding a way to allow DML-containing functions to be used in a safe and predictable manner, but before we do that it's imperative that we don't promote their use in new code.

**Comment by 1st1** [comment]
> We can add a configuration knob that enables the current behavior, e.g. CONFIGURE SYSTEM/SESSION SET allow_dml_in_functions := true (it'll be disabled by default).

Big +1. Let's allow early adopters to upgrade smoothly.

**Comment by CodesInChaos** [comment]
The simplest functions are pure, deterministic, do not access the database and always terminate normally. On top of that there are a bunch of additional capabilities a function could have:

1. Non determinism/read access to external state (randomness, current time, ...)
2. Read access to the database
3. Write access to the database
4. Write access to external state
5. Throw an exception
6. Run forever

Functions used in constraints cannot access to database and not determinism is generally a bad idea in constraints.

Functions mutating cannot be optimized out and can only be used in certain places.

IMO you should encode at least enough of the above properties in the function to decide if the function can be used in constraints or conditionals.

The minimal design which achieves that would be three types of function:
* `function` (pure, deterministic, can throw exceptions and run forever. Can be used in constraints and conditionals.
* `query` can also read from the database and be read external state/be non deterministic. Can not be used in constraints but can be used in conditionals.
* `mutation` can also write to the database and external state. Can neither be used in constraints nor in conditionals.

**Comment by 1st1** [comment]
> The minimal design which achieves that would be three types of function:

Actually this is an interesting way of looking at this problem. I specifically like the notion of "mutation" you suggested: a special kind of function where DML is allowed and with a set of restrictions on its call sites.

**Comment by 1st1** [comment]
@vpetrovykh That said, disabling DMLs in functions is high priority now; let's do that before a5. Also keep in mind: https://github.com/edgedb/edgedb/issues/1661#issuecomment-674288181.

**Comment by elprans** [comment]
> The minimal design which achieves that would be three types of function:

Yes, we already have a notion of function volatility, which intersects with these concerns.  It's unclear yet if we should equate `mutation` to `volatile`, though.

**Comment by tailhook** [comment]
> `mutation` can also write to the database and external state. Can neither be used in constraints nor in conditionals.

I would even say that we need a statement like `CALL create_new_session()` or `MUTATE WITH create_new_session()` and this is the only place where these functions can be used. Then these functions are as apparent as `INSERT`/`UPDATE`/`DELETE` statements and can be used in a same way (i.e. not a part of conditionals, ..etc)

**Comment by dmgolembiowski** [comment]
> > `mutation` can also write to the database and external state. Can neither be used in constraints nor in conditionals.
> 
> I would even say that we need a statement like `CALL create_new_session()` or `MUTATE WITH create_new_session()` and this is the only place where these functions can be used. Then these functions are as apparent as `INSERT`/`UPDATE`/`DELETE` statements and can be used in a same way (i.e. not a part of conditionals, ..etc)

Agreed.
A `MUTATE WITH` expression fits cleanly into the EdgeQL AST hierarchy:
```sql
WITH MODULE mod
MUTATE WITH session := mod::create_new_session(var_x)
SELECT
    mod::Session {
        id,
        created_at
    }
FILTER .id = session.id
```

**Comment by dmgolembiowski** [comment]
Hey @elprans, @vpetrovykh , and @1st1, it's been a hot minute since I've had the joy to work with EdgeDB. I'm trying to push its visibility at [  [insert my employer name here ]  ](https://tangramflex.com). With DML in function bodies being prohibited (for now), I was wondering / hoping either some stored procedure or dynamically-linked postgres FFI extension could be loaded. 

If you think there might be room for lowering one EdgeQL function-scope that contains multiple successive DML operations, I imagine there could be some magic to be unearthed if the transpiler stays in the confines of single-DML expression functions -- but decouples a large EdgeQL function scope into sub-routines (as single-op functions with random-looking names), then potentially ties the pieces together using some PL/SQL style stored procedure.  

Admittedly, I'm not very good with Postgres, so I don't know what it's limits and capabilities are, but if it doesn't allow procedure-like steps, perhaps a postgres extension could metaphorically "make the call from inside the house" -- going out to the external connection ingress -- and to keep things moving swifty hold the socket open or at least preserve the memory holding the UDS's int32 file descriptor(s) so that successive DML ops can happen without messing up the function counts.

I'd be curious to see if [aya-rs -> a Linux eBPF kernel module ](https://github.com/aya-rs/aya) could be useful here. Provided EdgeDB already _exclusively_ goes after Linux kernels 5.0+ , there might be room to get perform ant workarounds in userspace. 

---

Not that EdgeDB doesn't have incredible stuff going for it, I just found moving logic out to the database-layer cutting-edge af. I see a lot of room for growth and "software being indistinguishable from magic" if EdgeDB just lets users make functions that are enjoyable to write -- that work out of the box in any programming language since they're offloaded. It really is a big perk to me.

**Comment by mkhlsvn** [comment]
The inability to create conditional triggers limits the flexibility of the application. I tried to work around this limitation using the following approach. Unfortunately it didn't work.

function createL(app: LApp, event: LEvent) -> bool {
    volatility := "Volatile";
    using (
        WITH
            l:= (INSERT L {code:= app.code})
        SELECT true)
}

trigger create_L_after_D after insert for each do (
    assert(createL(__new__.app, __new__.event) if new.event = LEvent.D else true)
);

Perhaps there is some chance to make a special type of functions to support DML?

**Comment by ahirner** [comment]
> conditional triggers

Conditional triggeres [are supported](https://www.edgedb.com/docs/reference/ddl/triggers#example) in 4.0. 
However, using either pure functions with return values of custom object types or stored procedures for inserts/updates would much more ergonomic.
