### ISSUE TITLE
Implement INFER TYPE statement

### ISSUE THREAD

**Issue by vpetrovykh** [edgedb/edgedb#183]
Currently we don't allow properties or links on scalars and `__type__` seems to be breaking that general rule. Since scalars don't naturally define links, `__type__` is supported on them via hacky hardcode. One of the problems of that is that the type is then determined statically for scalars without any run-time polymorphism like object types have.

At the same time it seems like a good idea to introduce a `typeof` builtin function:
```
function std::typeof(OPTIONAL a) -> schema::Type:
  ...
```

These changes would also allow to have a consistent way of determining the type of empty sets. Consider the following:
```
WITH A := (SELECT User FILTER User.name = 'no such name')
SELECT A.__type__;

WITH A := (SELECT User FILTER User.name = 'no such name')
SELECT A.name.__type__;
```
Both of the above should return empty sets. With a `typeof` function we could instead write:
```
WITH A := (SELECT User FILTER User.name = 'no such name')
SELECT typeof(A);

WITH A := (SELECT User FILTER User.name = 'no such name')
SELECT typeof(A.name);
```

This would also enable to express the type of an arbitrary expression:
```
type Foo:
    property bar -> anyreal
    property baz -> anyreal
```
```
INSERT Foo {bar := 1.2};
INSERT Foo {baz := 3};
SELECT typeof(Foo.bar + Foo.baz);
```
In the above examples `Foo.bar + Foo.baz` would be `{}`, but of type `int64` and another of `float64`.

**Comment by 1st1** [comment]
There are some additional constraints on the `static_typeof` function:

1. It has to be a SET OF function, otherwise it's impractical to use it to introspect expressions.

2. It must accept an actual EdgeQL expression (and not a string!) because it's *static* and the compiler needs to always know what it is called on (preparing 'SELECT static_typeof($0)` is almost impossible to implement without hacks in the pipeline).

Therefore it has to be an operator accepting an EdgeQL expression:

```
   STATIC_TYPEOF <expr>
```

**Comment by 1st1** [comment]
Speaking of "INFER CARDINALITY" (for which we'll need a new issue), it would make sense for it to return `1` or `inf` so that it's possible to use comparison operators on its return values.

**Comment by 1st1** [comment]
Closing in favour of https://github.com/edgedb/edgedb/issues/219.
