### ISSUE TITLE
`UNLESS CONFLICT ON` fails in `FOR` statement 

### ISSUE THREAD

**Issue by unmade** [edgedb/edgedb#2295]
- EdgeDB Version: 1-beta1 (run in Docker)
- OS Version: macOS Big Sur 11.0.1

Steps to Reproduce:

1. Create schema
2. Run Select or Insert query in a FOR statement 

```edgeql
FOR title IN {'Blue Velvet', 'Mulholland Drive'}
UNION (
    INSERT Movie {
        title := title,
        director := (
            INSERT Person {
                name := 'David Lynch',
            }
            UNLESS CONFLICT ON .name
            ELSE (
                SELECT
                    Person
                FILTER
                    .name = 'David Lynch'
            )
        ),
    }
)
```
3. Query will fail with `ConstraintViolationError: name violates exclusivity constraint`

Schema:

```EdgeQL
START MIGRATION TO {
    module default {
        type Movie {
            required property title -> str;
            required link director -> Person;
        }

        type Person {
            required property name -> str {
                constraint exclusive;
            };
        }
    }
};
POPULATE MIGRATION;
COMMIT MIGRATION;
```

### Special notes

- This query works fine in `1-alpha7`
- If `Person` with target `name` already exists, than query runs fine
- Separate queries outside FOR...IN statement works fine

**Comment by 1st1** [comment]
@msullivan Sully can you take a look at this one?

**Comment by msullivan** [comment]
This behavior is maybe unfortunate but is intended and documented: https://www.edgedb.com/docs/edgeql/statements/insert

> A caveat, however, is that UNLESS CONFLICT will not prevent conflicts caused between multiple DML operations in the same query; inserting two conflicting objects (through use of FOR or simply with two INSERT statements) will cause a constraint error.

In the example case, you should be able to fix it by lifting up the nested insert outside the FOR statement using WITH.

I have a bunch of discussion about this issue in https://github.com/edgedb/edgedb/issues/2193, but basically the crux of the issue is that fixing it is probably possible, but technically pretty intricate and requires generating bigger and worse code.
