### ISSUE TITLE
Simplify edgedb concepts

### ISSUE THREAD

**Issue by DavidPratten** [edgedb/edgedb#2645]
See [The defininitions of all these terms](https://github.com/edgedb/edgedb/discussions/2642#discussioncomment-956577).

If the following terminology changes were introduced over coming versions, would the description above become simpler?

#### Server, system, and Instance
Within edgedb is it the case that the referent of `server`, `system` and `instance` are the same class of thing?  If so, what would happen if we migrated to using one term rather than three?  Here is an example, perhaps `edgedb server` could become `edgedb instance`.

#### Named Instance and Database
Within edgedb is it the case that a `named instance` is a 'connection, shortcut, or pathway' rather than a kind of `instance`? If so, what would happen if we shifted the name towards `instance connection` or something similar to make this explicit?

#### Named Instance and Default Database
Within edgedb is it the case that the `named instance` has as its referent the default database in the instance that is to be connected with?  If so, what would happen if we clarified that the `instance connection` (recommended above) always has an `instance` as its referent and that the CLI has a **behaviour** of using the default database when none is explicitly referred to?

All the best,

David

**Comment by elprans** [comment]
> Within edgedb is it the case that the referent of `server`, `system` and `instance` are the same class of thing?

`system` and `instance` _are_ the same, and it might be appropriate to consider renaming `CONFIGURE SYSTEM` to `CONFIGURE INSTANCE` for clarity.

`server` is a bit different, because we also use it to refer to a particular installed version of EdgeDB server, and `edgedb server` doesn't just manage instances, but also installations/updates of server packages on the system and each version may drive multiple instances.

> Within edgedb is it the case that a `named instance` is a 'connection, shortcut, or pathway' rather than a kind of `instance`? If so, what would happen if we shifted the name towards `instance connection` or something similar to make this explicit?

Well, an "instance", as in a physical server process and a data location, and an "instance connection" as in an instance file in `$XDG_CONFIG_DIR/edgedb/` usually have a 1:1 mapping on a given machine, e.g. you'd almost never have two "instance connections" to the same instance from the same machine, so I think it's simpler to continue to refer to both as "instance".

> Named Instance and Default Database

To clarify, "instance connections" don't actually have the name of a default database recorded.  The default database (usually "edgedb") is a convention that EdgeDB clients follow (PostgreSQL, for example, has the OS name of the current user as the default database name).

**Comment by DavidPratten** [comment]
Thanks Elvis,

Through this and other conversations I can see the changes that are in RFC1006 and related work and edgedb concepts are about to be simplifed.

The only question which is still open for me is the one above about named instances.  I'll open a specific issue around that.

Thanks for your response.
