### ISSUE TITLE
InternalServerError when selecting computed property created from link property

### ISSUE THREAD

**Issue by jaclarke** [edgedb/edgedb#3245]
- EdgeDB Version: 1.0-dev.6184+1833814

Steps to Reproduce:
```
edgedb> WITH
.......   __scope_0_Movie := (DETACHED default::Movie)
....... SELECT (__scope_0_Movie) {
.......   id,
.......   characters := (
.......     WITH
.......       __scope_1_Person := (
.......         SELECT __scope_0_Movie.characters {
.......           __linkprop_character_name := __scope_0_Movie.characters@character_name
.......         }
.......       )
.......     SELECT (__scope_1_Person) {
.......       name,
.......       single @character_name := (__scope_1_Person.__linkprop_character_name)
.......     }
.......   )
....... };
edgedb error: InternalServerError: more than one row returned by a subquery used as an expression
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      edb.errors.InternalServerError: more than one row returned by a subquery used as an expression
```

Schema: https://github.com/edgedb/edgedb-js/blob/a410b1630214db8dc2c19b71b94d26e6b348a917/qb/dbschema/default.esdl (with data inserted in test setup: https://github.com/edgedb/edgedb-js/blob/a410b1630214db8dc2c19b71b94d26e6b348a917/qb/test/setupTeardown.ts#L37)

**Comment by msullivan** [comment]
Looks like it doesn't require link props:
```
SELECT User {
  deck := (
    WITH
      U := (
        SELECT User.deck {
          foo := User.deck.name
        }
      )
    SELECT U {
      name,
      single z := U.foo
    }
  )
};
```
has the same problem.
This might mean it is related to `test_edgeql_scope_ref_outer_06`, though I'm not sure. This case *shouldn't* require materialization like that one does, so...

If `foo` is marked as multi, then lots of nonsense gets put into those rows.

If we make it `foo := .name`, it works.

Trying to do a partial path for the link property doesn't work, though, and gives `unexpected reference to link property 'rank' outside of a path expression`.
Turns out this is because it sees its root as `U` and not `User.deck`...
