### ISSUE TITLE
Don't allow changing user password in single user mode

### ISSUE THREAD

**Issue by fmoor** [edgedb/edgedb#3341]
Currently when postgres permissions don't allow creating users and the default user's password is changed it makes the provided `--backend-dsn` value invalid and subsequent backend connections fail. When running in single user mode changing the password should be banned.

**Comment by fantix** [comment]
After further thoughts and tests, comparing to using the pg_user's password as the EdgeDB user's password, I think we could decouple EdgeDB user's password from the pg_user's password in single-user mode. Because EdgeDB should consistently manage EdgeDB roles and passwords in different modes: in non-single-user mode, EdgeDB creates all the roles it uses, so it's okay to assume that the pg_user's password is in sync with EdgeDB user's password, and the user is not supposed to modify pg_user's password. In single-user mode however, the pg_user's password may possibly be e.g. reset by the managing cloud system, I think the password of the EdgeDB user shouldn't be affected. I'll create a PR.
