### ISSUE TITLE
EdgeDB roadmap

### ISSUE THREAD

**Issue by ansarizafar** [edgedb/edgedb#339]
EdgeDB is an amazing project and the time is right for EdgeDB to rule the database world. 

This project is under development for so many years but there is no visible roadmap.  A formal roadmap will greatly help to follow the development. 

We can use github projects https://github.com/sveltejs/svelte/projects/3 or an issue https://github.com/sveltejs/svelte/issues/622 to track the progress.

**Comment by 1st1** [comment]
Hi @ansarizafar, thanks for helping.  As you can see from the activity in the repo -- we're making a ton of refactorings and adding a lot of new features. Alpha 1 release is imminent. After we release alpha, we'll think about the format we want to use to have our roadmap in.  I'll close this issue for now so that it doesn't confuse people.
