### ISSUE TITLE
Default Values for required Enum fields not propagated to GraphQL API during migrate

### ISSUE THREAD

**Issue by maaft** [edgedb/edgedb#3444]
- EdgeDB Version: 1.0
- OS Version: ubuntu 20.04

Steps to Reproduce:

1. Add a person to you database
2. Add a new required enum field to your schema:
```diff
module default {
+  scalar type Color extending enum<Red, Green, Blue>;
   type Person {
     required property first_name -> str;
     required property last_name -> str;
+    required property color -> Color;
   }
}
```
3. `edgedb migration create`
Set default color to e.g. "Green":
```
Please specify an expression to populate existing objects in order to make property 'color' of object type 'default::Person' required:
fill_expr> "Green"
```
4. `edgedb migrate`
5. Query persons using EdgeQL:
```
edgedb> select Person {color};
{default::Person {color: Green}}
```
6. Query Persons using GraphQL
```
query {
  Person {
      color
  }
}
```

Error: 
```json
{
  "errors": [
    {
      "message": "QueryError: Field 'InsertPerson.color' of required type 'Color!' was not provided.",
      "locations": [
        {
          "line": 2,
          "column": 24
        }
      ]
    }
  ]
}
```

**Comment by vpetrovykh** [comment]
The message says: "...an expression to populate **existing** objects...". Basically it does exactly that and only that. The objects already present in the database at the moment of migration will get a new required property and that property value will be whatever you specify here. But no other changes will done. Crucially, no changes to the *schema* will be done, it will be *exactly* the schema you have in the SDL file. So no `default` will added to the `property color`. 

This is not a GraphQL issue.

If there's a wording that you think would make this clearer, please let us know.

**Comment by maaft** [comment]
I don't understand how this is not a graphql issue when I get the expected query results with edgeql but not with graphql.

**Comment by vpetrovykh** [comment]
I think somewhere along the line of experimenting with the REPL and GraphiQL (I assume you probably used GraphiQL to experiment with GraphQL queries, but it doesn't fundamentally matter which way you sent the queries to the server) you got mixed up on the exact sequence of steps and you thought you got an inconsistent result because of that. Allow me to illustrate:

1) I created a schema with just a `Person` and a `name`. Migrated.
2) Inserted a couple of `Person` records using edgedb CLI and GraphiQL.
3) So far so good, when I query them I get:
   ```
   edgedb> select Person{id, name};
   {
     default::Person {
       id: 0e60ac14-966f-11ec-b785-d3f6cb1840be,
       name: 'Alice',
     },
     default::Person {
       id: 2085981e-966f-11ec-84a8-c7ca08759cb5,
       name: 'Billie',
     },
   }
   ```
   and 
   ```graphql
   query {
     Person {
       id
       name
     }
   }
   ```
   returning
   ```json
   {
     "data": {
       "Person": [
         {
           "id": "0e60ac14-966f-11ec-b785-d3f6cb1840be",
           "name": "Alice"
         },
         {
           "id": "2085981e-966f-11ec-84a8-c7ca08759cb5",
           "name": "Billie"
         }
       ]
     }
   }
   ```
4) I add the enum and `color` property like your schema. Specify the value to populate the existing data with as "Green". Migrate.
5) Now the _queries_ of existing data yield:
   ```
   edgedb> select Person{id, name, color};
   {
     default::Person {
       id: 0e60ac14-966f-11ec-b785-d3f6cb1840be,
       name: 'Alice',
       color: Green,
     },
     default::Person {
       id: 2085981e-966f-11ec-84a8-c7ca08759cb5,
       name: 'Billie',
       color: Green,
     },
   }
   ```
   and 
   ```graphql
   query {
     Person {
       id
       name
       color
     }
   }
   ```
   returning
   ```json
   {
     "data": {
       "Person": [
         {
           "id": "0e60ac14-966f-11ec-b785-d3f6cb1840be",
           "name": "Alice",
           "color": "Green"
         },
         {
           "id": "2085981e-966f-11ec-84a8-c7ca08759cb5",
           "name": "Billie",
           "color": "Green"
         }
       ]
     }
   }
   ```
6) The error you're getting is from an `insert` operation (I can see it in the error message `"message": "QueryError: Field 'InsertPerson.color' of required type 'Color!' was not provided.",`, notice the `InsertPerson.color`). This is the input type used in the `mutation insert_Person` and it simply never appears as part of the "select" query interface.

   The _schema_ still doesn't have a `default` value for the `required property color`, so if I omit this value in an `insert` I expect an error.

   ```
   edgedb> insert Person{name := 'Cameron'};
   edgedb error: MissingRequiredError: missing value for required property 'color' of object type 'default::Person'
   ```
   and similarly in GraphQL
   ```graphql
   mutation {
     insert_Person(data: [{name: "Cameron"}]) {
       id
       name
       color
     }
   }
   ```
   gets me the same error you posted:
   ```
   {
     "errors": [
       {
         "message": "QueryError: Field 'InsertPerson.color' of required type 'Color!' was not provided.",
         "locations": [
           {
             "line": 31,
             "column": 24
           }
         ]
       }
     ]
   }   
   ```

I suspect that what happened is that you re-used a GraphQL mutation from the history that was inserting a `Person` without a `color` field. Or maybe you had all the named queries in one document and simply picked which one to run by name, accidentally running the insert mutation when you thought you were running a plain query. I think it's this kind of accident that's the source of confusion here and I hope this explanation clarifies it.

**Comment by maaft** [comment]
Thanks, I'll re-check next week and report back.
