### ISSUE TITLE
External UUIDs

### ISSUE THREAD

**Issue by amaster507** [edgedb/edgedb#3510]
Let's say I have data that already has a UUID from another source. Could I use that UUID as the id, or will edgeDB still create another UUID?

> Currently, it's prohibited.  Primarily because EdgeDB does not actually verify id uniqueness, so we can only trust ids we generate ourself. - @elprans

makes sense. I think this would be a good thing to have eventually though after a mechanism is added to verify uniqueness
I have data right now that has 2 unique ids from its previous and current data source. If I transition to edgeDB I will have to maintain these keys and also have a 3rd. Data syncs become more problematic because I have to either write back edgeDB id to my previous data source to know what exists already and what doesn't or use a different identifying field and do a insert of update statement. I see this becoming more problematic the more times one has to migrate their data between services that all generate their own unique identifiers.

> Verifying uniqueness is quite easy: `select BaseObject filter .id = <uuid>$id`. The problem is that it might be quite slow if you have a large database.  I hear your concern, though, so we'll think of something.
> Please open an issue - @elprans

**Comment by msullivan** [comment]
Yeah, we should be able to support this. It'll just be slower to insert if you provide your own `id` than if you don't.

**Comment by CodesInChaos** [comment]
Another important use-case is selectively restoring from a backup, for example because you accidentally deleted some data.

**Comment by Marnixvdb** [comment]
Does EdgeDB require the ID to be unique? If not, you could consider to make the check on global uniqueness optional, or to let the user define the scope that should be checked. Because if I provide the uuids, I can tell you where to look for duplicates. Brute-scanning the entire db would be overdoing it (even though it's a really nice optimisation problem to think about!).

**Comment by elprans** [comment]
Ids must be unique and there is no other way of ensuring that an externally-provided id is unique without scanning the database.  "Trusting" that it's unique isn't really an option.  All that said, even in a large database a global id scan isn't horrible, because it's a bunch of perfect index scans that are done in parallel.

**Comment by Marnixvdb** [comment]
Sure, it's not horrible, but it's still much more expensive than the uuid1 call EgdeDB currently uses. Not sure how that scales when the database grows?

What's the consequence of delegating the responsibility to provide unique IDs to the user, if they would explicitly chose to skip the check, for example using a --force flag or something similar? 

Anyway, maybe I'm better off in storing our uuids in a separate field, as my uuids are not sequential, like the uuid1s you generate. Lack of sequentiality  probably has a bigger impact on insert/indexing performance than EdgeDB having to scan all the indexes.
