### ISSUE TITLE
unresolved type: std::Movie_Type

### ISSUE THREAD

**Issue by cancan101** [edgedb/edgedb#3514]
- EdgeDB Version: 1.0.0
- OS Version: MacOs

Steps to Reproduce:

1. Setup the DB from the quick start: https://www.edgedb.com/docs/guides/quickstart
2. enable graphql
3. query graphql using:
```gql
query {
  Movie{
    id
    __typename
    ... on Movie_Type {
      id
    }
  }
}
```
recieve:
```
{
  "errors": [
    {
      "message": "AssertionError: unresolved type: std::Movie_Type"
    }
  ]
}
```

n.b. this works:
```gql
query {
  Movie{
    id
    __typename
    ... on BaseObject {
      id
    }
  }
}
```

Schema:
```
using extension graphql;

module default {
    type Person {
        required property first_name -> str;
        property last_name -> str;

        property full_name :=
        .first_name ++ ' ' ++ .last_name
        if exists .last_name
        else .first_name;
    }

    type Movie {
        required property title -> str;
        property year -> int64;
        link director -> Person;
        multi link actors -> Person;
    }
}
```

**Comment by cancan101** [comment]
The issue comes up when trying to use schema stitching as the `graphql-tools` library seems to insert a fragment which then triggers the error (at least when trying to extend the schema.
```js
  const ret = stitchSchemas({
    inheritResolversFromInterfaces: true,
    subschemas: [schema],
    typeDefs: /* GraphQL */ `
      extend interface Movie {
        foo: String
      }
      extend type Movie_Type {
        foo: String
      }
    `,
    resolvers: {
      Movie: {
        foo: () => "foo",
      },
    },
  });
```

**Comment by vpetrovykh** [comment]
> I'm not 100% sure why `Movie_Type` is the actual `type` whereas `Movie` is an interface. @vpetrovykh?

The reason why we primarily deal with interfaces rather than types is because every type can be extended. So `Movie` is not just all objects of type `Movie`, but also all objects of all possible `Movie` sub-types. Thus the best way to represent this in GraphQL is by an interface and not a concrete type. A concrete type is something only an object has, but in queries it's all about interfaces. So the correct solution is to use interfaces and not types in queries, fragments, etc.

Having said that, the fragments on types should obviously also work. The caveat here is that due to how EdgeDB treats types and GraphQL treats types fragments on "Something_Type" will apply as if they were on the underlying interface. In 99.99% cases I don't think this subtlety will make any difference.
