### ISSUE TITLE
Cardinality Inference on cascading

### ISSUE THREAD

**Issue by Jady891213** [edgedb/edgedb#3566]
- EdgeDB Version: 1.0
- OS Version: macOS Monterey 12.0.1

Steps to Reproduce:

1.I got a problem about cardinality Inference
![image](https://user-images.githubusercontent.com/71876021/156167349-40f3f3eb-ccb0-4f90-a331-5ff5a8cf1949.png)

- The red condition causes cardinality exception;
- The blue condition works

2.  related schema:
```  
create abstract type smartlist { 
    create required property name -> str;
    create property desc -> str; 
  };
  
  create type sml_cf_usage extending smartlist {
    alter property name {
      create constraint exclusive; 
    }; 
  }; 

  create type lease_asset { 
    create property sys_asset_id -> uuid; 
    create required property asset_no -> str { 
      create constraint exclusive; 
    };
    create property area -> decimal { 
      create constraint min_value(0); 
    } ;
    create property _create_time -> cal::local_datetime; 
    create property _modify_time -> cal::local_datetime; 
     
    create link entity -> dim_entity; 
    create link _creator -> user; 
    create link _modifier -> user; 
  };

  create type lease_cf_usage {
    create property lease_sdate -> cal::local_datetime; 
    create property lease_edate -> cal::local_datetime; 
    create property total_amount -> decimal; 
    
    create link cf_usage -> sml_cf_usage; 
    create required link asset -> lease_asset { 
      on target delete delete source; 
    } ;
    
    create constraint exclusive on ((.cf_usage, .asset));
  } ;

  create type lease_cf_payment { 
    create property cf_id -> uuid; 
    create property cf_date -> cal::local_datetime; 
    create property eff_sdate -> cal::local_datetime; 
    create property eff_edate -> cal::local_datetime; 
    create property cf_amount -> decimal; 
    create property cf_amount_calc -> decimal; 
    
    create link cf_type -> sml_cf_type; 
    create link cf_status -> sml_cf_status; 
    create required link lease_cf_usage -> lease_cf_usage { 
      on target delete delete source; 
    } ;
  } ;

```

Cardinality Inference on cascading has some problem.

**Comment by msullivan** [comment]
Taking a look. In the future, please post code snippets in as text, instead of sharing a screenshot, though. A screenshot makes it harder to try out the code.

**Comment by msullivan** [comment]
This is an interesting question. I think that I would categorize it as a "feature request" and not a bug report:

The current rules for cardinality inference is that if you filter on the exclusive constraints of an object, the cardinality will be AtMostOne. This means that as specified, the blue version is expected to work and the red version isn't, since it does not directly filter on the links with the exclusive constraints.

However, I think that it would be *sound* to allow filtering on longer paths, as long as each element of the path has an exclusive constraint on it.

That said, I think it is more important for the cardinality rules to be predictable to reason about than for them to cover every possible case. Extending it to cover longer paths like this is probably still pretty predictable to reason about, though?

To further complicate matters, while playing around with this idea, I discovered a bug in cardinality inference that actually does allow this sort of pattern to be accepted in some cases... including ones in which it is *not* sound.
For example, in our `cards` db, `select User filter .avatar.name = 'Dragon'` gets inferred as having `AtMostOne` because we misinterpret the `.name` and look up the name pointer on `User`, while totally ignoring the `.avatar` part.

So maybe we want to implement this feature along with the fix for that, to avoid breaking code that was depending on it and could be sound?

@elprans thoughts?

**Comment by msullivan** [comment]
Also, as a workaround, if you want to write the red version, you can surround the whole expression with `assert_single`

**Comment by Jady891213** [comment]
> So maybe we want to implement this feature along with the fix for that, to avoid breaking code that was depending on it and could be sound?
Thanks. I hope so.
