### ISSUE TITLE
Modifying a enum value defined as object default throws a migration error

### ISSUE THREAD

**Issue by lu-zen** [edgedb/edgedb#4053]
- EdgeDB Version: 1.4+5ffe34b
- OS Version: Linux lts

Steps to Reproduce:

1. Create a enum scalar and assign one of its values to a object property default;
2. Migrate;
3. Change the enum value on both enum definition and object default value;
4. migrate;

Schema:
```
module default {
scalar type TicketStatus extending enum<pending_assignment, Open, Closed>; # pending_assignment was previously Pending

type Ticket {
    property status -> TicketStatus {
        default := TicketStatus.pending_assignment; #Previously Pending
    }
}
}

```

Error: 
```
error: InvalidReferenceError: 'default::TicketStatus' enum has no member called 'Pending'
  ┌─ query:1:22
  │
1 │ CREATE MIGRATION m1s2iiin4awxnhdzrn5qp7upwqs6nv6dbyrmuuzjzizkrqq4oymtvq
  │                      ^^^^^^^^ did you mean 'Open'?

```

[Example repo](https://github.com/lu-zen/edgedb-enum-migration-bug)

**Comment by nsidnev** [comment]
Hi! This seems to have been fixed in one of the recent commits. The migration should now succeed if there are no entries in your database using the old enum member. If there are, the migration will fail with an `InvalidValueError` when applied to your database.

Therefore, in the second case, you should use a different migration style by performing the following these steps:
1. add a new member to your enum (i.e. `scalar type TicketStatus extending enum<pending_assignment, Pending, Open, Closed>` + use the new member as the default value in the type property
2. update entries to replace the existing `TicketStatus.Pending` with `TicketStatus.pending_assignment`
3. remove `TicketStatus.Pending` from the enum definition
 
These steps are necessary because EdgeDB can't control the presence of inserted types with the old value and be sure it can update everything on its own (since the old item will be gone), so you have to do it yourself.

Hope this helps :)

**Comment by lu-zen** [comment]
Hey, thanks! It seems to work just fine on 2.0-rc.2.
