### ISSUE TITLE
Empty set for a computed property

### ISSUE THREAD

**Issue by avedetvedea** [edgedb/edgedb#4304]
I have the following schema: 

```
type Athlete {
    required property firstName -> str {
        constraint max_len_value(30);
    };
    required property lastName -> str {
        constraint max_len_value(30);
    };
    property middleName -> str {
        constraint max_len_value(30);
    };

    required property fullName := 
        str_title(.firstName ++ ' ' ++ .middleName ++ ' ' ++ .lastName)
        if exists .middleName
        else str_title(.firstName ++ ' ' ++ .lastName);
}
```

There is a 'fullName' field, which will be computed-only. I marked it required anyway, as discussed in the docs, to make it explicit to myself.

I get the following error when I'm trying to migrate:
**Possibly an empty set returned by an expression for the computed property**

How is it possible to return an empty set in this case?

**Comment by msullivan** [comment]
It's not /actually/ possible to return an empty set in this case, but the cardinality inference is not smart enough to figure this out, since it won't interpret `if exists .middleName` to require that `.middleName` exists in that branch. It would be possible to implement that, but I don't think that we should, since I think it is more important for the cardinality inference rules to be simple and straightforward than it is for it to cover as many cases as we can think of.

You could add an `assert_exists` around the definition or you could do something like
```
    required property fullName := 
        str_title(.firstName ++ ' ' ++ ((.middleName ++ ' ') ?? '') ++ .lastName);
```
