### ISSUE TITLE
Cannot DROP CONSTRAINT

### ISSUE THREAD

**Issue by MicroDroid** [edgedb/edgedb#4343]
- EdgeDB Version: EdgeDB version "2" Docker image
- OS Version: Arch Linux

Steps to Reproduce:

1. `DROP` a `CONSTRAINT`

I couldn't put together a schema that reproduces the bug, but here's what I expected to reproduce it:

```
module default {
	type Entity {
		required property bucket -> str;
		required property available -> bool;
		required property assigned := .available and .bucket != 'UNPROCESSED';

		# To be removed
		constraint expression on (
			(.available and .assigned) or not (.assigned)
		);
	}
}
```

And here's the error that's thrown when `apply`ing the migration:

![image](https://user-images.githubusercontent.com/8523135/189599428-d50818d6-be39-4f61-b0e2-4e6148be7b52.png)

**Comment by elprans** [comment]
Are you able to attach your `dbschema/migrations` history?

**Comment by MicroDroid** [comment]
@elprans I work on the project for someone, and it's closed source, so I cannot do that.

**Comment by elprans** [comment]
The bug is likely path-dependent, i.e it's a combination of migrations that causes it.  If I had to reduce this, I would take the innards of all migrations, concatenate them (just the DDL, no `CREATE MIGRATION`), put inside `START TRANSACTION` ... `ROLLBACK` and then iterate to arrive at the smallest repro case.

(if possible, you can also send the migrations to me privately via a Discord DM or email).

**Comment by elprans** [comment]
You can pipe into `edgedb`:

```
edgedb> CREATE DATABASE testdb;
```

```
$ cat file.edgeql | edgedb -d testdb
```

**Comment by msullivan** [comment]
I'm going to close this because even though you clearly hit a bug, there's nothing actionable on our end right now. Sorry!
