### ISSUE TITLE
Problem with globals in a migration

### ISSUE THREAD

**Issue by 50l3r** [edgedb/edgedb#4428]
- EdgeDB Version: 2.0.5+da7c868
- OS Version: Windows 11

Hi guys, i have a problem with globals when i try to modify my schema. I recieve this error when i try to change link types.

```
error: UnsupportedFeatureError: globals may not be used when converting/populating data in migrations
   ┌─ query:20:7
   │
20 │ ╭       CREATE REQUIRED LINK created_by -> calltek::User {
21 │ │           SET default := (SELECT
22 │ │               calltek::User
23 │ │           FILTER
24 │ │               (.id = GLOBAL calltek::current_user_id)
25 │ │           );
26 │ │       };
   │ ╰───────^ error
```

Now i have a migration created but i dont know how can i rollback migration.

**Comment by elprans** [comment]
The error happens because you seem to be adding a new `required` link to an existing type.  When that happens, the system expects to be able to fill data for existing entries, but globals are not set in migration context.

Do the following:

1. Remove the latest-numbered file from `dbschema/migrations/` folder.
2. Change the schema default to not use a `global` and instead default to some other expression, e.g

```
   required link created_by -> User {
      default := (select User filter .id = <some_id>)  # or any other filter
   }
```

3. Create _another_ migration, changing the default to the containing the `global` reference.

**Comment by 50l3r** [comment]
Much thanks for your help. It works :)
