### ISSUE TITLE
on_demand compiler pool doesn't seem to scale up properly

### ISSUE THREAD

**Issue by msullivan** [edgedb/edgedb#4680]
1. Run `edb server --compiler-pool-mode=on_demand --compiler-pool-size=16`
2. Run `edb cli migration create` on a big schema that will take a while; I used the one from https://github.com/edgedb/edgedb/issues/4677
3. Try running `select 1` another cli.

It will hang for a long time. (It might sneak in somewhere in the middle of the migration, which is multiple commands.)

on_demand is the default for dev mode, so I was confused for a while. This reproduces without any compiler flags to `edb server` but I wanted to be explicit

**Comment by fantix** [comment]
The on_demand compiler pool only scales up when the **number of queued requests** goes up in a 3-seconds window. That means, the first `select 1` will only start the 3-seconds window (with 1 queued request) and you'll need a second `select 1+2` within 3 seconds to trigger the scale-up. This was designed to avoid scaling up for a busy-balanced scenario when the queue size is stable, but we can always change it (like count the starting queue size by 1 less so that we can adapt to the scenario mentioned in this issue).
