### ISSUE TITLE
Connection refused when generating Query Builder

### ISSUE THREAD

**Issue by jeremyjacob** [edgedb/edgedb#4687]
- EdgeDB Version: 2.6+ba1661b
- OS Version: Windows 11

Steps to Reproduce:

1. Create new edgedb instance via `project init`
2. Run `deno run --allow-all --unstable https://deno.land/x/edgedb/generate.ts edgeql-js`, as directed in the [docs](https://www.edgedb.com/docs/clients/js/querybuilder#generate-the-query-builder)
3. Throws network error: 

```
Generating query builder...
Detected tsconfig.json, generating TypeScript files.
   To override this, use the --target flag.
   Run `npx @edgedb/generate --help` for full options.
Introspecting database schema...
A client connection error occurred; reconnecting because of "waitUntilAvailable=30000". ClientConnectionClosedError: network error: ConnectionRefused: No connection could be made because the target machine actively refused it. (os error 10061)
    at RawConnection._onError (https://deno.land/x/edgedb@v1.0.1/_src/rawConn.ts:157:20)
    at TLSSocket.emit (https://deno.land/std@0.159.0/node/_events.mjs:379:28)
    at https://deno.land/x/edgedb@v1.0.1/_src/adapter.deno.ts:299:16
```
Seems to also be an issue using npx/pnpx. I can connect to the instance using the command line and web UI just fine. 
Starting the instance in the --foreground does not emit any ERROR level logging output.

**Comment by raddevon** [comment]
We've seen a similar issue (edgedb/edgedb-js#376). Sometimes Deno resolves `localhost` to `::1`. That might be what's causing your connection error since EdgeDB listens only on `127.0.0.1` by default.

Try `edgedb configure set listen_addresses 127.0.0.1 ::1` to get EdgeDB to listen on `::1` and see if you can then run the generator.

You might have to run `deno run --allow-all --unstable https://deno.land/x/edgedb/generate.ts edgeql-js --target=deno` if you get `Error: no syntax files found for target "cjs"`. That's a temporary workaround for a bug we're currently looking into.

**Comment by jeremyjacob** [comment]
This appears to have solved the error. Thanks!

**Comment by Kaustix** [comment]
thanks i was having the exact same issue in windows node, and this changing to localhost fixed the issue
