### ISSUE TITLE
Can't select link property via backlink

### ISSUE THREAD

**Issue by jamesbeck** [edgedb/edgedb#4704]
- EdgeDB Version: 2.7+a86e274
- EdgeDB CLI Version: 2.2.6+7eabbf9
- OS Version: MacOS 13.0.1 (22A400)

When trying to select a link property via a backlink the following error is returned:

`InternalServerError: column actors~1.25ee9fda-6af9-11ed-af36-2b332b67fd94 does not exist
Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md`

Steps to Reproduce:

1. Run this query on the EdgeDB example database:
`
select Person {
    name,
    roles := .<actors[is Movie] {
        title,
        @character_name
    }
}
filter .name = "Samuel L. Jackson"
`

Using EdgeDB Example DB Schema

**Comment by msullivan** [comment]
The bug has to do with inheritance. Running
```
select Person { name, roles := .<actors[is Content] { title, @character_name } } 
```
works fine.

The issue is that for the backlink traversal in the original query, we are joining in the link table view for `Content.actors` (which is correct (since we still join it against Movie), though suboptimal) but then try to read the column name for the `Movie` link property (which has a different name for `Movie` than for `Content`, since it is the id).

**Comment by msullivan** [comment]
The somewhat unfortunate
```
select Person { name, roles := (select .<actors[is Content] { title, @character_name } filter Person.<actors[is Content] is Movie) } 
```
works for now, I guess
