### ISSUE TITLE
"if orphan" documentation lacking and somewhat misleading

### ISSUE THREAD

**Issue by brassel** [edgedb/edgedb#4717]
- EdgeDB Version:
"2.7+a86e274"
- EdgeDB CLI Version:
EdgeDB CLI 2.2.6+7eabbf9
- OS Version:
macOS 12.6 (21G115)

Steps to Reproduce:

Run the following edgedb script in an empty database.

~~~
create module default if not exists;
create type default::Sub {
    create property name -> std::str;
};
create type default::Parent {
    create required link sub -> default::Sub {
        on source delete delete target if orphan;
    };
};
create type default::Parent2 {
    create link sub -> default::Sub {
        on source delete delete target if orphan;
    };
};
insert Sub {
  name := "sub 1"
};
insert Parent {
  sub := (select Sub filter .name = "sub 1" limit 1)
};
insert Parent2 {
  sub := (select Sub filter .name = "sub 1" limit 1)
};
delete Parent;
~~~

The result is 
~~~~
edgedb error: ConstraintViolationError: deletion of default::Sub (4e1116d8-6c9c-11ed-baf8-b3b891af78e4) is prohibited by link target policy
  Detail: Object is still referenced in link sub of default::Parent2 (4e1720d2-6c9c-11ed-baf8-b3f158647624).
~~~~

Schema:

**Comment by msullivan** [comment]
I believe this is working as intended, but our documentation fails to document the subtleties here:

`IF ORPHAN` means that we try to delete the target if the target object is orphaned *with respect to that link*. So because the `Sub` object is not pointed to by any other `Parent` object through the `sub` link, when `Parent` is deleted we try to delete the `Sub`, which then triggers `Parent2`'s constraint.
