### ISSUE TITLE
__subject__ does not work inside insert access policies

### ISSUE THREAD

**Issue by aldentepasta** [edgedb/edgedb#4733]
- EdgeDB Version: 2.7+5b16920
- EdgeDB CLI Version: 2.2.6+af56767
- OS Version: Ubuntu 22.04

Steps to Reproduce:

1. Declare a `User` object type, with no properties or links.
1. Declare a computed `global current_user` that resolves to a `User` object instance.
2. On the `User` type, create an `allow all` access policy such that `__subject__ ?= global current_user`.

This will fail with `there is no range var for ns~1@@(default::Redacted) value in <pg.SelectStmt at 0xDEADBEEF>`.

Schema:

```
using future nonrecursive_access_policies;

module default {
    global viewer_id -> uuid;
    global viewer := (select User filter .id = global viewer_id);
    
    type User {
        required property name -> str;

        access policy allow_self
            allow all
            using (__subject__ ?= global viewer);
    }
}
```

**Comment by msullivan** [comment]
I've reproduced this when doing `insert User { name := "foo" }` using this schema. Have you managed to get it with non insert queries?

This is certainly a bug, but this policy will also never be true for inserts. (Even if you do have an explicitly specified `id` and set `viewer_id` to it, `global viewer` won't resolve to it because it didn't already exist).

**Comment by aldentepasta** [comment]
You're right, I had simplified the schema a bit. The actual condition was `not exists global viewer or __subject__ ?= global viewer` and the test involved a double insert with no `global viewer_id` followed by a counting select with the `id` of one of the users assigned to `global viewer_id`.
