### ISSUE TITLE
RecursionError when compiling unions over many queries

### ISSUE THREAD

**Issue by 1st1** [edgedb/edgedb#475]
Query to repro:

```
WITH MODULE test
FOR X IN {
     (1,), (1,), (1,), (1,), (1,), (1,), (1,), (1,), (1,), (1,), 
     (1,), (1,), (1,), (1,), (1,), (1,), (1,), (1,), (1,), (1,), 
     (1,), (1,), (1,), (1,), (1,), (1,), (1,), (1,), (1,), (1,), 
     (1,), (1,), (1,), (1,), (1,), (1,), (1,), (1,), (1,), (1,), 
}
UNION 1;
```

**Comment by vpetrovykh** [comment]
Just to be clear, this bug can be reproduced on an even simpler query:
```
SELECT {
     (1,), (1,), (1,), (1,), (1,), (1,), (1,), (1,), (1,), (1,), 
     (1,), (1,), (1,), (1,), (1,), (1,), (1,), (1,), (1,), (1,), 
     (1,), (1,), (1,), (1,), (1,), (1,), (1,), (1,), (1,), (1,), 
     (1,), (1,), (1,), (1,), (1,), (1,), (1,), (1,), (1,), (1,), 
};
```

**Comment by 1st1** [comment]
**Targets:**

* Alpha 2: make sure codegen errors are serialized properly.
* Alpha 3: fix the bug, potentially by rewriting codegen to be non-recursive.

**Comment by msullivan** [comment]
Both of these work now, but adding an extra row makes it fail

**Comment by msullivan** [comment]
A few things:
 * It looks like the error does get serialized properly now
 * It's pretty fundamental to what we do that we are going to be recursing over user-provided nested data, so this sort of thing is always a risk
 * Python's default recursion limit is 1000, which is really not very big. It's probably worth turning it up.
 * If we want to make sure to prevent this sort of thing, one option is to have a check on the original AST that the nesting depth of constructs doesn't exceed some level, and then try not to blow up the nesting level beyond some factor during our compilation passes
 * This example in particular blows up the nesting level because we turn the set literal into a linearly deep chain of UNION operators. We could make it logarithmically deep by making it a tree of UNIONs instead of a list. (Though note that this is still incompatible with the above bullet point's suggest strategy which only permits a constant factor blowup.)

So I think my proposed plan for RecursionErrors is:
1) Turn up the recursion limit
2) Fix anything that seems to gratuitously blow up the nesting depth but otherwise don't worry too much at this stage

(That means fixing this one to not do a linear blowup of set literals)

**Comment by elprans** [comment]
Turning up the default recursion limit increases the risk of segfaults if the underlying C stack overflows instead, so we must pick the increase wisely.

> one option is to have a check on the original AST that the nesting depth of constructs

Blowing up with a reasonably-explained `RecursionError` is fine.  Postgres itself doesn't shy from this:

```
elvis-# \e
ERROR:  stack depth limit exceeded
HINT:  Increase the configuration parameter "max_stack_depth" (currently 2048kB), after ensuring the platform's stack depth limit is adequate.
```

> This example in particular blows up the nesting level because we turn the set literal into a linearly deep chain of UNION operators. We could make it logarithmically deep by making it a tree of UNIONs instead of a list. 

Or fold the entire chain into a single `N`-ary operation.  It'd lead to better codegen too, which, by the way is where the recursion depth gets multiplied through extra levels of SQL relation nesting.

**Comment by 1st1** [comment]
> Turning up the default recursion limit increases the risk of segfaults if the underlying C stack overflows instead, so we must pick the increase wisely.

TBH I'd keep the limit as is and try to fix our algorithms.

> Or fold the entire chain into a single N-ary operation. It'd lead to better codegen too, which, by the way is where the recursion depth gets multiplied through extra levels of SQL relation nesting.

+1.

**Comment by elprans** [comment]
> TBH I'd keep the limit as is and try to fix our algorithms.

Well, set literals are an obvious thing to special-case, but things become much harder if you imagine a huge arithmetic expression (e.g. a thousand additions or subtractions or a mix thereof).  Reimplementing the compiler and all visitors without recursion is a daunting task.  I'd still consider carefully bumping the recursion limit in the compiler process if the current limit turns out to be problematic in practice.  

As an aside, I think CPython is being lazy by only providing the recursion *depth* as a knob and not the actual stack size limit like Postgres does.
