### ISSUE TITLE
Support link properties on computed backlinks

### ISSUE THREAD

**Issue by msullivan** [edgedb/edgedb#4825]
In our `cards` test database, 
```
select Card { owners: { @count } };
```
ought to work

(Currently we can access properties on backlinks when they are spelled out explicitly, but not via computeds)

**Comment by coreyward** [comment]
I was coming to ask about this since I need to be able to access a link property from either direction (i.e., from either of the target objects). Is there a reasonably efficient workaround available? This is my first time working with link properties in EdgeDB and some of the syntax is unfamiliar.

**Comment by omnunum** [comment]
Would love to see this make its way in.  Not a huge issue since the link props can still be accessed, but it definitely reduces the convenience and value of having computed backlinks.



> Is there a reasonably efficient workaround available?

@coreyward For the time being you need to reference the backlink explicitly (recreate it in every query).

I have the following types
```
type Person {
    property name -> str;
    multi link employers := .<employees[IS Company];
}

type Company {
    required property name -> str;
    multi link employees -> Person {
        property employment_title -> str;
    }
}
```

I can't run 
```
select Person { 
    name, 
    employers: {
        name,
        employment_title := @employment_title,
    } 
}
;
```
Due to `InvalidReferenceError: link 'employers' of object type 'default::Person' has no property 'employment_title'`

But I can run 
```
select Person { 
    name, 
    employers := .<employees[IS Company] {
        name,
        employment_title := @employment_title,
    } 
}
;
```

And get data back.

----
@msullivan what confuses me is why I can overload the computed backlink in the above scenario but not this one
```
select Person { 
    name, 
    employers := .<employees[IS Company] {
        name,
        @employment_title
    } 
}
;
```
I receive the same error as above.  Any insight?

**Comment by msullivan** [comment]
It's a bug; part of the cause for that last one not working is that it has the same name as the computed link in the schema that doesn't work properly. Honestly the thing that surprises me the most is that the one before that still works even though the name is still the same.

3.0 will have it working in the schema.
