### ISSUE TITLE
Simultaneous total deletion of related objects fails in the presence of multi links

### ISSUE THREAD

**Issue by stealth-toucan** [edgedb/edgedb#4836]
- EdgeDB Version: `2.9`
- EdgeDB CLI Version: Irrelevant
- OS Version: Irrelevant

Steps to Reproduce:

1. Migrate to the schema below using `start migration to ...; populate migration; commit migration;`.
2. Run query A below.
3. Run query B below.
4. Step 3 will fail with `ConstraintViolationError: deletion of default::B (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx) is prohibited by link target policy`

It's unclear to us if this is considered a bug (Query C succeeds), however a similar setup with single links succeeds regardless of the order of deletion. If this is not considered a bug, the burden of the topological sort falls to the end-user.

Schema:

```
module default {
  type A {
    required multi link x -> B;
  }
  
  type B;
}
```

Query A:

```
with
  a := (insert B),
  b := (insert B),
  c := (insert A {
      x := {a, b}
  })
select {
  c := c
}
```

Query B:

```
with
  a := (DELETE B),
  b := (DELETE A)
select {
  a := a,
  b := b
}
```

Query C:

```
with
  a := (DELETE A),
  b := (DELETE B)
select {
  a := a,
  b := b
}
```

**Comment by msullivan** [comment]
I think it is debatable whether this is a "bug" but I think it would be an improvement if we fixed it, certainly.

**Comment by msullivan** [comment]
The issue here has to do with how multi links (and properties) are represented and how we use triggers to enforce link target policies.
Triggers are used for several things in the implementation, including:
1. Enforcing link target policies. When an object is deleted, a trigger checks if any incoming links exist and fails if so. (Or allows it, or deletes the source, depending on the policy.)
2. Deleting entries from a link table on source object deletion. A multi link is stored as a table with `(source, target)` rows. When an object is deleted, a trigger fires that deletes all link table entries with the object as source.

These triggers all run after the query, and they are triggered in the order the objects were modified.
So for query B, triggers are run in the following order
1. On the deletion of each B, a link target policy checks the link table for `A.x` to see if the object is a target
2. On the deletion of each A, all the entries in `A.x` with each A as source are deleted

This fails, because when step 1 runs, the link table entries haven't been deleted yet. In query C, those steps are reversed and so it works. The single link case works because for single links, the link lives in the source row, which got deleted in the actual query.

I know of two possible fixes here:
1. Make the link target policy trigger join against the source object instead of just checking the link table. Since the source object is gone, it won't fail.
2. Delete entries from the link tables in the actual query, instead of relying on triggers to do it.

We should do option 2. Option 1 would make all link policy checks slower. Option 2 on the other hand would make most deletes *faster*, since we could get rid of the need for the triggers.
Option 1 is included really just in case there is some reason why option 2 won't work that I'm not thinking of.
I think it should be pretty straightforward to do.
