### ISSUE TITLE
Free object selection of update nested inside for loop throws an error

### ISSUE THREAD

**Issue by PastelStoic** [edgedb/edgedb#4875]
- EdgeDB Version: 2.7+81de4dd
- EdgeDB CLI Version: 2.2.6+af56767
- OS Version: Multiple (windows and linux)

Steps to Reproduce:

1. With any existing schema, pick an object type and run the following:
```
select {
  updateData := (assert_distinct((for item in {"itemone", "itemtwo"} union (
    (update ObjectType set {})))))
}
```

The result will be `InternalServerError: missing FROM-clause entry for table "expr-1~2"`.

**Comment by msullivan** [comment]
The bug here is that we are inserting a volatility ref into the CTE we generate for the iterator, to make sure it is evaluated for every object that the shape is over.

Of course, the shape is a literal free object, will only have one element, and so doesn't need to iterate (which is why we allow DML in the shape, when we don't allow it in other select shapes), so it shouldn't need a volatility ref.
