### ISSUE TITLE
Filter `or` condition traversing relationship to self breaks filtering

### ISSUE THREAD

**Issue by jackfischer** [edgedb/edgedb#4894]
- EdgeDB Version: 2.9+4fbadd2 and 3.0-dev.7171+c75f4a2
- EdgeDB CLI Version: 2.2.6+7eabbf9
- OS Version: macos 13.1 (22C65)

Steps to Reproduce:

1. Insert an object with an empty optional relationship to itself
2. Query for the object and its children, original object is not returned

```
EdgeDB 2.9+4fbadd2 (repl 2.2.6+7eabbf9)
Type \help for help, \quit to quit.
edgedb> insert StrategyNode {tiptapId:="root"};
{default::StrategyNode {id: c39a261e-95f1-11ed-b318-c7e0172a1c74}}
edgedb> select StrategyNode {id, tiptapId, parentNode} filter .id =<uuid>'c39a261e-95f1-11ed-b318-c7e0172a1c74'; # No problem
{default::StrategyNode {id: c39a261e-95f1-11ed-b318-c7e0172a1c74, tiptapId: 'root', parentNode: {}}}
edgedb> select StrategyNode {id, tiptapId, parentNode} filter .id =<uuid>'c39a261e-95f1-11ed-b318-c7e0172a1c74' or .parentNode.id =<uuid>'c39a261e-95f1-11ed-b318-c7e0172a1c74'; # Strictly more flexible filter
{}
```

Schema:

```
module default {

    type StrategyNode {
        link parentNode -> StrategyNode;
        required property tiptapId -> str {
            constraint exclusive;
        };
    }
}
```

**Comment by jaclarke** [comment]
This is actually the intended behaviour. Since `parentNode` is empty, the expr `.parentNode.id =<uuid>'c39a261e-95f1-11ed-b318-c7e0172a1c74'` evaluates to an empty set `{}`, so the whole `or` expression becomes `{}`.

To get the behaviour you want, you can use the `??` operator like this:
```
filter .id =<uuid>'c39a261e-95f1-11ed-b318-c7e0172a1c74' or (.parentNode.id =<uuid>'c39a261e-95f1-11ed-b318-c7e0172a1c74' ?? true)
```
There's a cheatsheet here that gives more details: https://www.edgedb.com/docs/guides/cheatsheet/boolean.

**Comment by jackfischer** [comment]
Got it. Thanks James.
