### ISSUE TITLE
Implement mutation rewrites RFC

### ISSUE THREAD

**Issue by msullivan** [edgedb/edgedb#4937]
https://github.com/edgedb/rfcs/blob/master/text/1021-rewrites.rst

**Comment by aljazerzen** [comment]
@1st1 @msullivan We forgot to decide how rewrites interact with defaults:

```
create type Movie {
	create required property title -> str {
		set default := 'untitled';
		
		create rewrite insert using (
			'specified' if __specfied__.title else 'not specified'
		)
	};
};
```

What happens when I `insert Movie {};`? Are defaults applied first or are rewrites applied first?

I'd say rewrites, which means that:

```
insert Movie {};
select Movie { title };
-- Movie { title: "not specified" }
```

It follows that if you have both default and rewrite on a pointer, default will never get executed, since property will always be specified - even if rewrite returns an empty set.

**Comment by aljazerzen** [comment]
As discussed with Sully, it's more convenient to have default be applied first. See https://github.com/edgedb/rfcs/pull/80
