### ISSUE TITLE
Add some way to run SQL administration commands like ANALYZE and REINDEX

### ISSUE THREAD

**Issue by msullivan** [edgedb/edgedb#4938]
The main complications here are annoying syntactic things:

* Maybe we want to put them all in some heading, like `ADMINISTRATE`, instead of adding a lot of new bare commands
* But there is nothing like `ADMINISTRATE` that would make a good reserved keyword
* `ANALYZE` and `REINDEX` are already reserved
* If we don't allow `WITH` bindings before the commands, we can use a non-reserved keyword

So I guess my proposal is to add `ADMINISTRATE ANALYZE` and `ADMINISTRATE REINDEX` as commands, and to disallow the use of `WITH` before them.

We can even make `ANALYZE` and `REINDEX` non-reserved.

(My main direct use case here is that I want to run `ANALYZE` after we create the database in the explain test case)

**Comment by vpetrovykh** [comment]
I think that `ADMINISTRATE` is not a very clear choice of keyword to be used as an umbrella term. I'm not sure how `ANALYZE` and `REINDEX` fit under this umbrella, while `ROLE` commands do not. It may be that we're trying to distinguish commands that are used to configure how EdgeDB works vs commands that are involved in maintenance. Perhaps a `SYSTEM` umbrella might be a better indicator that the commands there are more about system maintenance than configuring day-to-day operation. Generally we can expect any future maintenance command to be a verb and follow `SYSTEM <VERB>` pattern.

**Comment by vpetrovykh** [comment]
`ANALYZE` command in Postgres has several levels of granularity: everything, table, and column. In EdgeDB we would like to have similar granularity, but since we don't have tables and columns, we would specify it in terms of Objects and individual pointers.

The most general usage would still be just `ANALYZE` without any parameters. It would collect statistics on all the database contents.

The next level of granularity would be `ANALYZE Foo` where `Foo` denotes some object type. This is roughly equivalent to `ANALYZE <table>` in Postgres, however there are some notable differences. Since out objects may include things like multi links, the data about the object may be spread across several tables (one for the core properties and such, plus one for each of the link tables). 

The final level of granularity is at the link or property level. The basic format would be `ANALYZE Foo.bar`. Link properties would always be included in the analysis as long as their parent link is included and would never need to be specified explicitly. It's not clear there's much benefit to extending this granularity to allow specifying just the link property as the target of the command, although syntactically, it's also possible to provide this option.

It would make sense to use shapes to specify what needs to be analyzed so `ANALYZE Foo {bar}` or even `ANALYZE Foo {bar, other: {ham, spam}}` may be acceptable. The shape would effectively be a way of listing one or more related tables that need to be processed. 

We can keep the two optoins "VERBOSE" and "SKIP_LOCKED". Postgres suggests that each of these options can also be given an explicit boolean value to toggle it (omitting the boolean value implies that the option is turned on). Although I understand the usefulness of that in scripts, maybe we should consider hoe to best handle that in EdgeDB.

**Comment by vpetrovykh** [comment]
`REINDEX` in Postgres applies to "INDEX", "TABLE", "SCHEMA", "DATABASE" and "SYSTEM". It seems that in EdgeDB we can map "INDEX", "TABLE", and "DATABASE" to `INDEX`, `TYPE`, and `DATABASE`, respectively. We don't quite have a "SCHEMA", although we do have modules, but internally we would still have to list every object in the module subject to reindexing in order to apply a module-wide command. Reindexing the "SYSTEM" probably works out similarly in EdgeDB as it does in Postgres, although we might need to include some more EdgeDB-specific internal tables for reindexing.

The options for this command are "CONCURRENTLY", "TABLESPACE", and "VERBOSE". It's not clear that the "TABLESPACE" option can be translated into EdgeDB, although the other two seem to be at least meaningful.
