### ISSUE TITLE
Missing source position on a 'cannot reference correlated set' error

### ISSUE THREAD

**Issue by divan** [edgedb/edgedb#5019]
I'm trying to do nested UPDATE  and get the error 'InvalidReferenceError: cannot reference correlated set ... here'

Schema:

```esdl
module default {
    type Foo {
        required link bar -> Bar {
            constraint exclusive;
        };
    }

    type Bar {
	property baz -> int32;
    }
}
```

Query:

```EdgeQL
UPDATE Foo 
SET {
  bar := (UPDATE .bar SET {baz := <int32>42})
}
```

**Error InvalidReferenceError: cannot reference correlated set 'Foo' here**

I'm not sure if I'm doing nested updated correctly. Found this approach here: https://github.com/edgedb/edgedb/discussions/2392

I'd love to understand what that error means and how to properly do the recursive update with current version.

- EdgeDB Version: 2.9+4fbadd2
- EdgeDB CLI Version: 2.2.6+7eabbf9
- OS Version: MacOS 13.1 (22C65)

**Comment by msullivan** [comment]
Argh, it doesn't have a source position in it, which is definitely a bug.

EdgeDB won't let you refer to something in an outer scope like `Foo` from inside an inner mutation statement.
You could do something like
```
UPDATE Foo                                                                      
SET {                                                                           
  bar := (with b := Foo.bar, UPDATE b SET {baz := <int32>42})                   
};
```
There are also various ways you could rewrite it to not use an `update` on Foo, since nothing is actually changing.

You could do `UPDATE Foo.bar SET {baz := <int32>42};` (though that will return something different)
Obviously in real life probably you have a filter on Foo, so you'd make it a subquery or something WITH-bound.

**Comment by msullivan** [comment]
Keeping this bug open to track the missing source context.

Also `cannot reference correlated set` here is a terrible error message and we need to make it better.

**Comment by divan** [comment]
Thanks @msullivan! `UPDATE Foo.bar ...` works and in a way even more expressive!
