### ISSUE TITLE
No TLS Option for Reverse Proxies

### ISSUE THREAD

**Issue by kyuuaria** [edgedb/edgedb#5030]
Add an option to disable TLS for serving the admin ui behind a reverse proxy. I believe this should definitely be an feature and would make things much easier.

**Comment by raddevon** [comment]
Got some information on this today. It turns out, you're already able to disable TLS on the server by launching with `edgedb-server —http-endpoint-security=optional`. That should do what you want to do, although we don't recommend it because it leaves your connection to the EdgeDB endpoint unencrypted. Just make sure you're aware of that before you proceed.

I'll go ahead and close this since the option is already available, but let me know if you feel this doesn't address your issue.

**Comment by kyuuaria** [comment]
That leaves me to wonder why the `EDGEDB_SERVER_HTTP_ENDPOINT_SECURITY` env var isn't documented properly. It's just in the 1.0 RC 2 changelog.
