### ISSUE TITLE
Warn or require an expression after defined Access Policy is incompatible with existing data

### ISSUE THREAD

**Issue by avedetvedea** [edgedb/edgedb#5244]
If an Access Policy is introduced (say on Insert and Update Write) that a `User` of type `A` can only define `a` and of type `B` can only define `b` properties, however a data exists in the DB that a `User` of type `A` has their field `b` defined, then trying to update that user to either `a` or `b` will result in Access Policy violation, which is often hard to debug, since one has to set them at the same time to figure out that initial data was incompatible. A warning in the migration may appear if something similar to `fill_expr` is unfeasible

**Comment by msullivan** [comment]
I don't think this makes sense to do in general, since in general, access policies can (and probably usually *will*) refer to global variables.
I think that you're using them as a generalized constraint, and in that case this sort of warning could be useful, but I think that's probably too niche of a use case here.

**Comment by avedetvedea** [comment]
I see. This is my first time using Access Policies so maybe I will come learn that
