### ISSUE TITLE
`InternalServerError: Can't find materialized set` when referencing free object from an INSERT

### ISSUE THREAD

**Issue by scotttrinh** [edgedb/edgedb#5312]
Seems similar to #5287 but doesn't resolve when I remove any/both `assert_single` calls.

- EdgeDB Version: 2.13+ad0eb0f
- EdgeDB CLI Version: 2.3.1
- OS Version: macOS Ventura 13.3

Steps to Reproduce:

Run the following (mostly) reduced query:

```
WITH
  playlists := { "cool video playlist", "lofi hip hop beats" },
  seq := { name := "Cool and Lofi", steps := { (video := "cool video playlist", audio := "lofi hip hop beats") } }
SELECT (
  WITH
    new_playlists := (FOR playlist IN playlists UNION (INSERT Playlist { url := playlist } UNLESS CONFLICT ON Playlist.url ELSE Playlist))
  INSERT Sequence {
    name := seq.name,
    step := (
      FOR step IN seq.steps UNION (INSERT Step { 
        video := assert_single((SELECT new_playlists { id } FILTER (new_playlists.url = step.video))),
        audio := assert_single((SELECT new_playlists { id } FILTER (new_playlists.url = step.audio)))
      })
    )
  }
)
```

Schema:

```
type default::Playlist {
  property url -> std::str {
    constraint std::exclusive;
  };
};

type default::Sequence {
  property name -> std::str;
  multi link step -> default::Step;
};

type default::Step {
  required link audio -> default::Playlist;
  required link video -> default::Playlist;
};
```

**Comment by msullivan** [comment]
Even more minimized:
```
WITH                                                                      
  seq := { name := "Cool and Lofi" }                                      
SELECT (                                                                  
  INSERT Sequence {                                                       
    name := seq.name,                                                     
  }                                                                       
);
```

**Comment by msullivan** [comment]
The issue is caused by referencing the free object from inside the INSERT.

This issue is kind of an annoying tangle because:
1. We currently don't support referencing volatile WITH bound variables from inside DML (https://github.com/edgedb/edgedb/issues/2809)
2. In order to make sure that the randomly generated `id` of a free object works properly, we treat free object construction as volatile when deciding how to compile things (discussed https://github.com/edgedb/edgedb/issues/4886 a little)
3. But we *don't* treat it as volatile for diagnostic purposes, since that would be very annoying, but that results in us failing to produce an error message.

I think we maybe should stop treating free objects as volatile, like I discussed in #4886. It's not /really/ sensible, but we can document it, and nobody will ever care.

**Comment by scotttrinh** [comment]
@msullivan Is there a straightforward work around to avoid the free object in this query? My approach here is taken directly from the docs at https://www.edgedb.com/docs/clients/js/for#bulk-inserts but I haven't checked to see if that query suffers from the same issue.

**Comment by dnwpark** [comment]
The issue can be reproduced with a simplified schema and query.

Schema:
```
type Person { property name -> str };
```

Query:
```
with x := { name := "Foo" } insert Person { name := x.name };
```
