### ISSUE TITLE
Cardinality bug fixes can leave migration state wedged

### ISSUE THREAD

**Issue by msullivan** [edgedb/edgedb#5321]
This is a general class of problems we face, along with a specific way that a 2.13 bugfix triggers it. This is minimized from an actual user issue.

Create and migrate to this schema in 2.12:
```
module default {
    type Foo {
        required multi property spam -> str;
        property eggs := (select .spam);
    }
};
```

Then, upgrade to 2.13, and run `edgedb migration create` again (with no changes):
```
$ edgedb migration create
edgedb error: EdgeDB could not resolve migration with the provided answers. Please retry with different answers.
```

If we run with `EDGEDB_DEBUG_DELTA_PLAN=1`, we get some insight into the situation:
```
================================================================================
DESCRIBE CURRENT MIGRATION AS JSON mismatch
================================================================================
<DeltaRoot canonical=True at 0x7f2793600670> (
    <AlterObjectType canonical=True, classname=default::Foo, annotations={'confidence': 1.0}, orig_cmd_type=<class 'edb.schema.objtypes.AlterObjectType'> at 0x7f2793601690> (
        <AlterProperty canonical=True, classname=default::__|eggs@default|Foo, annotations={'confidence': 1.0}, aux_object_data={'from_alias': None} at 0x7f2791ca4160> (
            <AlterPropertyLowerCardinality classname=default::__|eggs@default|Foo at 0x7f2791ca5540>(required=False | True # computed)
        )
    )
)
```

We can see that `Foo.eggs` in the database has `required=False` but that we want it to have `required=True`, and we fail to create a migration.

----

The issue here is that in 2.13, we fixed a cardinality inference bug: https://github.com/edgedb/edgedb/pull/5180
and as a result, `eggs` infers a different cardinality in 2.13 than in 2.12. This creates a mismatch between the actual live schema and the schema that we create in 2.13, and so we aren't able to do any migrations.

Making a trivial change to `eggs` lets us recover from this state, since that will cause it to get re-inferred directly.

Of course, there is no good way for an actual user to discover that really simple workaround, so this is kind of a mess.

Dump/restore also would work, I think
----

I'm not sure what the best approach to this category of issues is. I'm not sure that we can reasonably rule out these kinds of changes.

I think we might need some sort of repair tool. Maybe a command that does something along the lines of computing what the schema *should* be (from `describe` output, maybe), comparing that to the actual schema, and just making the fixups.

**Comment by raddevon** [comment]
If we build such a fixup tool, can it run automatically if a `migration create` fails in a way that could indicate this problem? I guess the question is maybe

- Can we detect the state that would require a fixup, or can we detect a migration error that indicates a schema might be impacted by this bug?
- What is the likelihood of false positives on that detection?
- How much of a burden would it be to run a fixup for all schemas that might be affected when they attempt to create a migration?

Alternatively, could we proactively run a fixup on an upgrade from 2.12 to 2.13?

I know I'm putting the cart before the horse here a little since a fixup tool doesn't yet exist, but I want to get these ideas on the table in hopes to minimize the burden on users if we do build it.

**Comment by elprans** [comment]
IMO there should be a best effort automatic fixup at upgrade time a-la stdlib patches.  In other words, if we break the state in this way with a bugfix in 2.x, we should try and unbreak it in 2.x+1.
