### ISSUE TITLE
Re-execute the function on conflict

### ISSUE THREAD

**Issue by deounix** [edgedb/edgedb#5362]
Is there any way to re-execute the function on exclusive property when there's a conflict ?

Something like this ?

```
module functions {
    function GenerateCode () -> str using (select (<str>std::uuid_generate_v1mc())[-12:]);
}

module mixins {
    abstract type HasReferenceCode {
        annotation description := "Defines a mixin for adding a 'reference_code' property to a type.";

        required property reference_code -> str {
            default := (
                with generate_code := (select functions::GenerateCode())
                insert self::HasReferenceCode {
                    reference_code := generate_code,
                }
                unless conflict on .reference_code retry
            );
            readonly := true;
            constraint exclusive;
        }
    }
}

module core {
    type User extending mixins::HasReferenceCode {

    }
};
```

**Comment by aljazerzen** [comment]
The sort answer is no, there is not.

Your proposal would not word even if implement the `unless conflict retry`, because `with` binding would not execute your function again, but would use the same value that was generated the first time.

Looking at your snippet, that would trigger a "type error: reference_code is of type str, but default has type HasReferenceCode". You probably wanted something like this:

```
module functions {
    function GenerateCode () -> str using (select (<str>std::uuid_generate_v1mc())[-12:]);
}

module mixins {
    abstract type HasReferenceCode {
        annotation description := "Defines a mixin for adding a 'reference_code' property to a type.";

        required property reference_code -> str {
            default := (select functions::GenerateCode());
            readonly := true;
            constraint exclusive;
        }
    }
}

module core {
    type User extending mixins::HasReferenceCode {

    }
};

insert User {} unless conflict on .reference_code retry;
```
This code would need the `unless conflict` on every insert statement, though.

As a workaround, you could have something like:
```
insert User {} unless conflict on .reference_code else (insert User {});
```
... but that could produce a conflict in the second insert and you'd have to do:
```
insert User {} unless conflict on .reference_code else (
  insert User {} unless conflict on .reference_code else (
    insert User {} unless conflict on .reference_code else (
      insert User {}
    )
  )
);
```
... having enough inserts so the chance of conflict is low enough. This is still imperfect and you'd probably want to have a loop that has as many inserts as needed.

We will probably not add such `retry` iteration because it is a very convenient way of creating infinite loops. Imagine that your function would produce only 128 different values for example. When you'd reach 128 users, all insert queries would start looping infinitely.

So my suggestion is to either:
- have a function that does not have conflicts (i.e. sequential numbers or a full UUID),
- handle this on the client side with a proper retry loop.
