### ISSUE TITLE
count() triggering access policy erroneously

### ISSUE THREAD

**Issue by jerber** [edgedb/edgedb#5394]
- EdgeDB Version: 3.0-dev.7392+c8cd47e
- EdgeDB CLI Version: 2.3.1+5d93f42
- OS Version: Digital Ocean deployment (Ubuntu 20.04)

I have a query:
`select SlotToFill FILTER <str>$auth_id in .venue.owner_firebase_ids`. For user xxx (using access policies) this works and returns the slots. However, if I wrap this query in a count:
`select count((select SlotToFill FILTER <str>$auth_id in .venue.owner_firebase_ids))`
the `select` access policy is triggered and the query fails -- even though it shouldn't.

It doesn't make sense that the first query would execute successfully but counting the results would trigger the access policy. Are there special permissions needed for `count`?

**Comment by aljazerzen** [comment]
Seems like this is a bug. Can you also include the schema that you are using?

**Comment by msullivan** [comment]
We discussed this out-of-band, and the issue was that a `select` access policy was calling `assert` to try to make failing the policy an error instead of a silent failure.

This doesn't really work because it will be very sensitive to how postgres plans the query.

Raising an error on a select access policy failing *is* a useful thing to do, but it's unfortunately a pretty awkward fit for the relational/object-relational query model. We'll need to think carefully about whether there's a good way to support that kind of workflow.
