### ISSUE TITLE
Unless conflict misbehaves when conflict occurs and the caller lacks select access on the object

### ISSUE THREAD

**Issue by hbriese** [edgedb/edgedb#5504]
- EdgeDB Version: `2.14+7aec755`
- EdgeDB CLI Version: `2.3.1+ef99779`
- OS Version: `Ubuntu 22.04`

Steps to Reproduce:

1. Insert object - works as expected
```
insert T { name := "abc" } unless conflict
```

2. Run the same query
```
insert T { name := "abc" } unless conflict
```

This time it errors with `ConstraintViolationError: name violates exclusivity constraint`.

Expected behaviour: 

Object isn't inserted as it already exists, and an empty set is returned

Schema:
```
type T {
    required property name -> str {
      constraint exclusive;
    }

    access policy anyone_can_insert
      allow insert;
  }
```

**Comment by hbriese** [comment]
Nothing is thrown when the caller has select access on the object
i.e.
```diff
type T {
    required property name -> str {
      constraint exclusive;
    }

+   access policy anyone_can_select
+     allow select;

    access policy anyone_can_insert
      allow insert;
  }
```

**Comment by msullivan** [comment]
This is working as intended. Because the conflicting object is not visible, `UNLESS CONFLICT` cannot see it in order to determine not to insert.

The alternative design possibility would have been for the `INSERT` to be prevented, but for the `ELSE` clause (if it exists) to not actually receive the conflicting objects (since that would *badly* leak information). We decided that having ELSE not actually return the conflicting object was a big enough downside that we shouldn't do it, and we felt the existing behavior made more sense.

It's true that some information leaks here, but `UNLESS CONFLICT` doesn't have much to do with that. You get the same information leak on just a plain `INSERT`, and if `UNLESS CONFLICT` prevented the insert in this case you would get the information leak because you could check if the `INSERT` actually returned something.

Importantly though, this potential leak only happens if the INSERT is *allowed*. If a potential insert is disallowed by policy, then the policy will fail before an exclusive constraint violate is reported.

Hope that all makes sense; feel free to reopen if you have a follow-up.
