### ISSUE TITLE
ISO 8601 -> `cal::local_date` casting

### ISSUE THREAD

**Issue by jackfischer** [edgedb/edgedb#5601]
ISO 8601 strings are very common. Currently, in order to use them with EdgeDB `cal::local_date` you have to parse the string and reconstruct the `cal::local_date`. It would be helpful to just cast strings to `cal::local_date`, similar to the existing behavior for `std::uuid`.

**Comment by elprans** [comment]
Why not use (`to_local_date()`)[https://www.edgedb.com/docs/stdlib/datetime#function::cal::to_local_date]?

**Comment by jackfischer** [comment]
Ah I see. I don't fully understand the philosophy of when conversions are functions vs casts (maybe the potential variation in formats is the decision maker here) though I think the `uuid` behavior is lowest friction.

**Comment by vpetrovykh** [comment]
Could you bring up a few examples of the strings that aren't working?
```
edgedb> select <cal::local_date>'2023-05-07';
{<cal::local_date>'2023-05-07'}
edgedb> select <cal::local_date>'20230507';
{<cal::local_date>'2023-05-07'}
```
The basic `YYYY-MM-DD` format works (with and without the dashes). Are you trying to use a string that also has a time component? An example would really help clarify what problem you're running into.

**Comment by jackfischer** [comment]
Ah, casts _do_ exist? This problem was occurring in QB. 
```typescript
e.params({example: e.cal.local_date}, $=>...).run(client, {example: "2020-01-01"});
```

`Type 'string' is not assignable to type 'LocalDate'.ts(2322)`

**Comment by vpetrovykh** [comment]
In case you just have a string already and you don't want to parse it in the client code the pattern is something like this in EdgeQL:
```
select Foo filter .date = <cal::local_date><str>$example
```
Notice the two chained casts here. The one adjacent to the parameter `$example` is mandatory and is not actually a cast as much as it is a type declaration for the [query parameter](https://www.edgedb.com/docs/edgeql/parameters). This declaration is pretty strict and it basically tells EdgeDB what are you sending over the wire and what it should expect to decode. The outer cast is simply a cast , which will work fine as long as it's legal to cast between the parameter type and whatever new type you specify there.

So you would want to do something along the lines of:
```ts
e.params({example: e.str}, params =>
  ... 
  e.cast(e.cal.local_date, params.example) 
  ...
).run(client, {example: "2020-01-01"});
```

You should use `edgedb.LocalDate` to [instantiate](https://www.edgedb.com/docs/clients/js/literals#dates-and-times) a value for an `e.cal.local_date` parameter if the raw data you have is already a bunch of integers that are used to compose the date, so that you don't have to parse anything on the client.

We don't have a convenience function to convert a string to an  `edgedb.LocalDate` value in the client code, though.

**Comment by jackfischer** [comment]
Many thanks for all the information. What is the difference between the pattern above and the `e.uuid` behavior where the cast appears to happen automatically? Is the convenience function you mentioned actually something that would happen silently when a string is passed in as an `e.uuid` param and is the difference maker?

**Comment by elprans** [comment]
Hm, could be an oversight.  I think all types that support string casts should have a JS constructor function taking a string.  But this really an edgedb-js issue now, so moving this thread there.
