### ISSUE TITLE
Change how globals are passed in GraphQL

### ISSUE THREAD

**Issue by vpetrovykh** [edgedb/edgedb#5863]
Currently global variables are passed as their own special `globals` field. This is a non-standard field and it gets in the way of existing frameworks and libraries.

An alternative to that would be to use the `variables` field that's part of the GraphQL standard and add `__globals__` to that.

**Comment by jnak** [comment]
Sweet. When is this going to be released?

**Comment by msullivan** [comment]
> Sweet. When is this going to be released?

That's a good question. We have an implementation of it that is probably ready to merge to master and so could be in nightlies basically immediately, but I'm considering whether we should wait until 4.0 to actually release it, because in a way it is a compatibility break, with potential security implications.

In particular, if anybody is running an HTTP proxy server that proxies untrusted graphql queries to edgedb (using access policies to restrict access), and the proxy server sometimes passes *no* globals argument, then a client would be able to specify `__globals__` and inject globals that they should not have been able to.

On the flip side, I'd be kind of surprised if anybody is actually doing that. 
We have an example of this sort of proxy (https://github.com/edgedb/edgedb-examples/blob/main/flask-proxy/app/main.py), which I don't know if anybody has ever looked at (and which *always* passes `globals` so wouldn't have this problem.)

**Comment by jnak** [comment]
I appreciate you carefully assessing compatibility and security implications. We are actually using a proxy / stitched schema like in the Flask proxy (using Typescript, though), and it could indeed create a security problem if not rolled out properly. 

It's probably the right call to wait for EdgeDB 4.0 at this point. Thanks!

**Comment by dvv** [comment]
I wonder whether there is a way to pass globals to `edgeql_http` as well?
