### ISSUE TITLE
InternalServerError: could not serialize result in worker subprocess

### ISSUE THREAD

**Issue by Geomitron** [edgedb/edgedb#5947]
- EdgeDB Version: "3.2+99ce519"
- EdgeDB CLI Version: 3.4.0+160d07d
- OS Version: Ubuntu 22.04 (LTS) x64

I'm getting the error:
"InternalServerError: could not serialize result in worker subprocess. Hint: This is most likely a bug in EdgeDB."

Steps to Reproduce:

Run the query in the attached edgeql.txt file:
[edgeql.txt](https://github.com/edgedb/edgedb/files/12422148/edgeql.txt)
(Note: this query was generated by the Typescript query builder)

Schema:
[default.esdl.txt](https://github.com/edgedb/edgedb/files/12422175/default.esdl.txt)

**Comment by raddevon** [comment]
Have you re-generated the query builder since you updated? If not, that may be worth trying. I use `npx @edgedb/generate@latest edgeql-js` to make sure I'm generating with the latest query builder generator.

**Comment by Geomitron** [comment]
Yes, the query builder was on the latest npm version (0.3.3 as of today)

**Comment by raddevon** [comment]
OK. Are you saying that you have installed the latest query builder generator or that you have re-generated your query builder since upgrading and that you used the latest version to do that?

**Comment by Geomitron** [comment]
The latest query builder is installed and was used to generate this query. Regardless of the answer, I don't think any edgeql query should have such an obscure error message; I have no idea what to change to fix it.

**Comment by elprans** [comment]
`InternalServerError` is always a server bug, I don't think the generator is to blame here.

**Comment by msullivan** [comment]
Almost certainly the problem is that the query is too big along some dimension and we're choking on it.

I think the problem here is the big array literals. You'd probably be better off passing them as query arguments.

I think there are probably a couple different problems here:
 * When we stack overflow in the compiler, we fail to report it out in a useful way. We should report that we failed from a stack overflow.
 * We should turn our python recursion limit up. With the number of intermediate nodes our AST contains and the number of wrapper functions in the pg compiler path, I think we can have on the order of 10 call frames per nesting level in the original AST
 * We should fix places where flat constructs in the original query end up generating big nested constructs. For arrays of non-trivial values, it looks like the problem is that we compile each element in a subquery and then cross join them all together. We always represent joins as a binary `JoinExpr` node, so a seemingly flat list of joins becomes a linearly deep tree.

**Comment by msullivan** [comment]
Points 1 and 3 above are basically duplicates or existing issues, and I've filed a new bug about the recursion limit. So I'm closing this in favor of:
 * #4677
 * #6002
 * https://github.com/edgedb/edgedb/issues/4380
