### ISSUE TITLE
Computed scalar not found in SQL protocol, metabase can't show table

### ISSUE THREAD

**Issue by jackfischer** [edgedb/edgedb#6017]
- EdgeDB Version: 3.2
- EdgeDB CLI Version:
- OS Version: 

Steps to Reproduce:

1. Query for the fields in a table, computed scalar is returned (`userPolicyDecision`)
```sql
SELECT 
 *
FROM 
  information_schema.columns
WHERE 
  table_name = 'AuditLog';
```

2. Query a computed scalar
```sql
select "userPolicyDecision" from "AuditLog";
```

```
ERROR: cannot find column `userPolicyDecision` Position: 126
```

In metabase, this manifests as trying to open the table and receiving the following error,
<img width="780" alt="Screenshot 2023-09-01 at 5 47 27 PM" src="https://github.com/edgedb/edgedb/assets/6811459/995df69c-e3f9-4a21-ba71-793931ab1c67">

Schema:
```
    scalar type UserPolicyDecision extending enum<a, b>
    type AuditLog {
        property userPolicyDecision := .message.userPolicyDecision;
        link message := .<auditLog[is Message];
    }
    type Message {
        single link auditLog -> AuditLog;
        property userPolicyDecision -> UserPolicyDecision;
    }
```

**Comment by aljazerzen** [comment]
I'm unable to reproduce this issue on EdgeDB 3.2 and the latest master (using Postgres 14.3)

The `information_schema` query returns a single row: the id. The computed property is skipped, as expected.

Metabase also connects, scans the schema and queries the two tables correctly.

Please provide more details on how to reproduce the issue.

**Comment by aljazerzen** [comment]
PS: I've ran Metabase with:

```
docker run -d -p 3000:3000 --name metabase --net=host metabase/metabase
```
... which started Metabase version v0.47.2 (536c24c release-x.47.x)

**Comment by jackfischer** [comment]
Thank you, will set up a better repro on 4.0 when that's released in case it is somehow solved there

**Comment by jackfischer** [comment]
Fixed as of 4.2. Metabase no longer picks up `userPolicyDecision`.

**Comment by jnak** [comment]
Are you planning to add computed fields to the SQL interface? It would be such a killer feature to have ORM-level computed properties flow to analytics platforms and low-code tools.  That's the dream of any data engineering team.

**Comment by aljazerzen** [comment]
We are not planning to do that, but we can reconsider if there is more interest for it.

Without a proper though, it seems to me that this should not be hard to implement. The hardest part would (probably) be introspection (`pg_catalog` and `information_schema`.

There might be conceptual blockers though, for example "should these columns appear in pg_dump?".

**Comment by jnak** [comment]
@aljazerzen If it's a relatively low lift, I highly encourage you to implement it since this would solve the biggest pain point between engineering and data teams. The logic defined in ORMs never makes it to BI tools/warehouses and has to be re-implemented by data engineers in ETL who need the proper business context. For example, in our case, we use a reverse-ETL to export some of our EdgeDB in a customer engagement platform (called customer IO), and now we have to re-model all that logic in SQL there. It also impeded our ability to iterate on our DB models since schema changes in EdgeDB cannot be deployed in synchronicity across all systems. 

Honestly, this ability to have computed values automatically available in the auto-generated GQL schema has been one of our favorite features since it allows us to encapsulate all our READ business logic in EdgeDB. We're crushed it's not available in SQL 😞
