### ISSUE TITLE
Problem with reverse links

### ISSUE THREAD

**Issue by vpetrovykh** [edgedb/edgedb#603]
Unrelated links with same name and target result in errors when accessing the reverse link.

See test `test_edgeql_ddl_inheritance_alter_03` (#602)

**Comment by pedronc** [comment]
I am not sure if it's possible to resolve the conflict without changing the current syntax. I have been experimenting with links and reverse links and I think the current syntax is kind of confusing. 
Consider this schema: 
```
TYPE Actor {
	REQUIRED PROPERTY name -> str;
};

TYPE Movie {
	REQUIRED PROPERTY name -> str;
	MULTI LINK actors -> Actor;
};
```
A nice way to transverse the link forward (i.e. get the actors in the movie) and backwards (i.e. get the movies the actor starred in) could be: 
```
SELECT Movie {
	name,
	total_actors := count(SELECT Movie.>Actor)
}

SELECT Actor {
	name,
	starred_in := (SELECT Movie.<Actor)
}
```

If an object have more than one link of the same type, the syntax can be extended to something like: 
```
TYPE Movie {
	REQUIRED PROPERTY name -> str;
	MULTI LINK main_actors -> Actor;
	MULTI LINK secondary_actors -> Actor;
};

SELECT Movie {
	name,
	count_main_actors := count(SELECT Movie[main_actors].>Actor)
}
```

**Comment by elprans** [comment]
The correct way to disambiguate the link traversal is to use the [type filter expression](https://edgedb.com/docs/edgeql/funcops/set#operator::ISFILTER):

```
TYPE Movie {
	REQUIRED PROPERTY name -> str;
	MULTI LINK main_actors -> Actor;
	MULTI LINK secondary_actors -> Actor;
};

SELECT Movie {
	name,
	count_main_actors := count(SELECT Movie.main_actors[IS Actor])
}
```

Also, the result of a reverse link traversal is a union type of all possible targets (although the implementation of this is currently incomplete):

```
type Movie {
    multi link actors -> Actor;
}

type Play {
  multi link actors -> Actor;
}

SELECT Actor.<actors; # <-- the type of this expression is (Movie | Play)
```

To narrow the type:

```
SELECT Actor.<actors[IS Play]
```

We actually had a similar syntax to that you are proposing very early on, but it was quickly replaced with the current approach.  The reason is that you don't normally use a subtype for every relation, so there would be a generic `Person` type, not an `Actor`, and you will end up using link names anyway.

**Comment by 1st1** [comment]
@elprans what should we do with this one?

**Comment by elprans** [comment]
The original issue was fixed, so closing this.
