### ISSUE TITLE
group query causes InternalServerError: Can't compile ref to visible binding

### ISSUE THREAD

**Issue by freeatnet** [edgedb/edgedb#6059]
- EdgeDB Version: 3.3+d5734dd
- EdgeDB CLI Version: 3.5.0+e1ad387
- OS Version: macOS 13.5.2

Steps to Reproduce:

1. Apply the schema below
2. Run the query specified below

Expected: result or a user-fixable error
Observed: `InternalServerError: Can't compile ref to visible binding ns~1@@(__derived__::g~1)`

**Schema:**
```esdl
module default {
  scalar type MessageType extending enum<amplify>;

  type Message {
    required identity: str;
    required type: MessageType;
    required href: str;

    required title: str;
    required timestamp: int64;

    required signer: str;
    required signature: str {
      constraint exclusive;
    }

    constraint exclusive on ((.identity, .href, .type));
    index on ((.href, .timestamp));
  }
}
```

**Query:**
```edgeql
with
  groups := (group Message by .href)
select groups {
  id,
  keyMessage := assert_exists(
    (
      select .elements {
        id,
        href,
        title,
        identity,
        timestamp,
        signature,
      }
      order by .timestamp asc
      limit 1
    ),
    message := "key message not found"
  ),
  points := count(.elements),
  upvoters := array_agg(.elements.identity),
}
order by .keyMessage.timestamp desc
offset <int64>$from
limit <int64>$amount
```

**Comment by jollygreenlaser** [comment]
Unfortunately I managed to lose the query that was causing it but I hit this issue too. Never tried outside of UI. 

It seems the issue is selecting a property on a custom shape. So on this query I'm guessing it's the `order by .keyMessage.timestamp desc`. I had something similar on mine - no `group` but added a computed property then `thing.computed` later to make a set - and refactoring that away fixed the issue.
