### ISSUE TITLE
Fill-out pg_catalog introspection SQL adapter

### ISSUE THREAD

**Issue by msullivan** [edgedb/edgedb#6403]
`pg_class` has an `attnum` field that we should probably treat like `ordinal_position`

There are also `pg_table` and `pg_view` views that maybe we need to intercept?

**Comment by aljazerzen** [comment]
You probably mean "`pg_attribute` has an `attnum` column". I've fixed that in #6507, because it was tripping pg_dump when `attnum` were not sequential, which was happening when `__fts_document__` got hidden.

`pg_tables` and `pg_views` remains to be done.

Can I assume we can hide all views outside pg_catalog and information_schema?

For `pg_tables` I intend to pull data from our `edgedbsql.virtual_tables`.
