### ISSUE TITLE
Select query using with block returns null if an attribute is set to empty/null

### ISSUE THREAD

**Issue by s0l4r** [edgedb/edgedb#6442]
- EdgeDB Version: 4.0+0335ddb
- EdgeDB CLI Version: EdgeDB CLI 4.0.1+bf01004
- OS Version: MacOS Ventura 13.6

Steps to Reproduce:

1. Query an existing product, with a null value set for the url

```
with product := (
  select Product
  filter .id = <uuid>'d1b2bd18-7b17-11ee-b404-7fbb83a34fa3'
)
select <json>(
  id := product.id,
  title := product.title,
  url := product.url
)
```

Incorrectly returns: `{}`, if url is null.

2. A working query for the same object is

```
select <json>(
  select Product {
    id,
    title,
    url,
  }
  filter .id = <uuid>'d1b2bd18-7b17-11ee-b404-7fbb83a34fa3'
)
```

Correctly returns:
```
{Json("{\"id\": \"a10f2d24-7cd2-11ee-9685-d3b4ef921f33\", \"title\": \"Test\", \"url\": null}")}
```

3. Select another product with url value set

```
with product := (
  select Product
  filter .id = <uuid>'a10f2d24-7cd2-11ee-9685-d3b4ef921f33'
)
select <json>(
  id := product.id,
  title := product.title,
  url := product.url,
)
```

Correctly returns:
```
{
  Json("{\"id\": \"a10f2d24-7cd2-11ee-9685-d3b4ef921f33\", \"url\": \"https://test.com\", \"title\": \"Test 2\"}"),
}
```

Schema:

```
  abstract type HasTitle {
    required property title -> str;
  };

  abstract type HasUrlOptional {
    optional property url -> str;
  };

  type Product extending HasTitle, HasUrlOptional {
    index on (.title);
  }

```

See discussion on Discord at: https://discord.com/channels/841451783728529451/1171480425504448544/1171505408649732206, this might be the issue.

**Comment by jaclarke** [comment]
This is actually the intended behaviour. What you're constructing here in parentheses is a named tuple (https://www.edgedb.com/docs/stdlib/tuple#constructing-tuples), as I think was mentioned in the discord thread:
```
(
  id := product.id,
  title := product.title,
  url := product.url
)
```
Since tuples are primitive types, every element in it must be a single primitive value. So this, along with the fact that 'null' in edgeql is represented as an empty set, means that 'null' values in a tuple effectively collapse the whole tuple to an empty set. It may make more sense if you consider how constructing tuples with multi-set elements behaves, where it creates a set containing the cartesian product (https://www.edgedb.com/docs/reference/edgeql/cardinality#cartesian-products) of all the elements:
```
# multi set elements get expanded out to a set of tuples each with single value elements
edgedb> select (a := {1, 2}, b := 3);
{(a := 1, b := 3), (a := 2, b := 3)}

edgedb> select (a := {1, 2}, b := {3, 4, 5});
{(a := 1, b := 3), (a := 2, b := 3),
(a := 1, b := 4), (a := 2, b := 4),
(a := 1, b := 5), (a := 2, b := 5)}

# likewise an empty set get 'expanded' to an empty set of tuples
edgedb> select (a := {1, 2}, b := <int64>{});
{}
```

If you want to do a query with a `with` var as in the first example, you can instead use a free shape (https://www.edgedb.com/docs/edgeql/select#free-objects), as these create a free object type on the fly, the fields of which can contain sets:
```
edgedb> select {a := {1, 2}, b := 3};
{{a: {1, 2}, b: 3}}
```
or for your example:
```
with product := (
  select Product
  filter .id = <uuid>'d1b2bd18-7b17-11ee-b404-7fbb83a34fa3'
)
select <json>{
  id := product.id,
  title := product.title,
  url := product.url
}
```
