### ISSUE TITLE
Need explanation how to retrieve newly insterted link

### ISSUE THREAD

**Issue by MrFoxPro** [edgedb/edgedb#6465]
- EdgeDB Version: https://packages.edgedb.com/archive/x86_64-unknown-linux-gnu/edgedb-server-4.1%2B2194ddc.tar.zst
- EdgeDB CLI Version: 4.1.0-dev
- OS Version: x86_64 GNU/Linux 6.6.1-arch1-1

With following schema:
```edgeql
type Dialog {
   required num: ChatsNumericSequence { readonly := true; constraint exclusive; };
   multi members: User { on target delete allow; };
   multi messages: Message {
      constraint exclusive;
      on target delete allow;
      on source delete delete target;
   }
   index on (.num);
}
type Message {
   required num: MessagesNumericSequence { constraint exclusive; readonly := true; };
   index on (.num);
   from: User { on target delete delete source; };
   single link chat := .<messages[is Dialog];
   required text: MessageText;
}
```
I want to insert new `Message` inside chat object and retrive message with updated link `chat`
```edgeql
with
  chat := (select Dialog filter .num = <int64>$target_num),
  message := (insert Message { from := me, text := msg_text }),
  updated_chat := assert_single(( update chat set { messages += message } ))
 select ???
```
1) If I `select message { chat_num := .chat.num }`, then I have empty `chat_num`.
2) I can do `{ chat_num := chat.num }`, but it's quite inconsistent and inconvinient, because I use template literals for selecting fields from type and it's what backlink is for.
3) `select detached Message filter .id = message.id` returns empty set, however, message have `id` field.
4) I found `select updated_chat.messages { chat_num := .chat.num } filter .id = message.id` works, but why, will it work in other cases and what is a correct way to get newly inserted item as link?

**Comment by aljazerzen** [comment]
Queries 1 and 3 might be a bug, I have to talk about it with @msullivan

Your query 2 is probably the way to go here, I cannot think of a better expression.

**Comment by LukeLaScala** [comment]
Any update on this @aljazerzen @msullivan? Running into the same issue as above and unsure how to construct a decent workaround.

**Comment by msullivan** [comment]
Query 3 is not a bug, but query 1 looks like it probably is. I'll take a look.

**Comment by msullivan** [comment]
Oh, looking closer, query 1 is *not* actually a bug, though this is a little subtle.
I think your best bet is going with option 2.
Another approach that might serve you better is reversing the link direction, and having a single link from `Message` to `Dialog`.

`insert` and `update` return the newly created/updated objects, but doing a `select` on that type (like in query 3) won't return the newly inserted data, since it won't be "visible" in the database until after the query. 
In query 1, it is easy to argue that it shouldn't be visible: the update to `chat` hasn't happened yet even, so the backlink definitely shouldn't see it.

Query 4 is a trickier case. Arguably it *also* shouldn't work.
* In the implementation, the reason it works is because when we go to compute `chat` (which expands to `.<messages[is Dialog]`), we see that its source is `updated_chat.messages`, and that `updated_chat` is an update, and so we include that update in the "overlay" we join against for the `messages` link.
* But semantically, I'm not sure that this makes sense. In the formalization the semantics that @zchenb has made, I'm pretty sure that backlinks *always* just look at what was in the database at the start of the query, and never at what has been done by updates. I'm not sure if there is a reasonable way to formally explain why query 4 works, which probably indicates that query 4 should *not* work.

**Comment by MrFoxPro** [comment]
> Another approach that might serve you better is reversing the link direction, and having a single link from Message to Dialog.
Wdym? There is computed single link from Message to Chat

**Comment by MrFoxPro** [comment]
Do you mean to remove Chat.messages and leave only link from Message to Chat (non computed then)?
