### ISSUE TITLE
Add schema-level exclusive assertions

### ISSUE THREAD

**Issue by PastelStoic** [edgedb/edgedb#6527]
Given the following schema (from the example in the docs):
```
type User {
  required username: str;
  required clean_username := str_trim(str_lower(.username));

  constraint exclusive on (.clean_username);
}
```

The expression `select User filter .username = <str>$username` has a cardinality of 0 or 1, as the computed constraint prevents duplicates from existing - however, the compiler cannot infer that, requiring `assert_single` to be added to queries. Asking the compiler to detect when a computed constraint does or does not allow duplicates is likely too complex, but allowing us to add something like `assert_exclusive` to the property would be useful.

**Comment by msullivan** [comment]
I think the best thing to do here is to actually add `constraint exclusive` to `username`. That will get you the behavior you want, *and* it will create an index on `username` so that the query you gave is fast

In theory we could add an `assert_exclusive` type thing where we inject `assert_single` when the property is filtered on, but it is hard for me to think of when using it would be an improvement over actually adding the exclusive constraint.

I'm going to close this, but feel free to reopen with a comment if you think I'm missing something!
