### ISSUE TITLE
Plans for fulltextsearch?

### ISSUE THREAD

**Issue by OhBonsai** [edgedb/edgedb#660]
Is there any plan for fulltext-search?  or implement it by posgtres-plugin or edgedb plugin?

**Comment by elprans** [comment]
Yes.  We will publish the roadmap soon.

**Comment by shackra** [comment]
@elprans there is no mention of full-text search on the current roadmap https://edgedb.com/roadmap/

**Comment by TheNoim** [comment]
So, it isn't planned anymore? I was really excited when I read through the docs of edgedb and couldn't wait for the 1.0 release. But without fulltext search I lost some of my excitement.

**Comment by elprans** [comment]
Support for FTS is definitely coming, but not before 1.0.  Our goal is to make FTS in EdgeDB extensible, so that you're not constrained by PostgreSQL's FTS only and can bring an external indexer like ElasticSearch.  This makes it a more complex feature to design and implement.

**Comment by TheNoim** [comment]
But why isn't it then on the roadmap?

**Comment by elprans** [comment]
> But why isn't it then on the roadmap?

We'll have a big update to the website soon, including the updated roadmap.

**Comment by TheNoim** [comment]
I mean, it seems like it is now the updated page, but I can't find ft on the roadmap. And in the docs I can't find anything to ft either. I don't want to be impolite :) For the beginning it would maybe be nice to at least have things like tsvector etc.

**Comment by kelvin2200** [comment]
Amazing.. that's all i've got! We're excited about EdgeDB because we're in the initial phase of building a multi-tenant project, and we're still at the point where we can switch our DB and logic however... FTS is a deal-breaker for us. It will probably take some time before we're going to need it but i'd like to know if there's a real initiative of implementing it in EdgeDB, and of course if it will be implemented in say... a year?

**Comment by 1st1** [comment]
> It will probably take some time before we're going to need it but i'd like to know if there's a real initiative of implementing it in EdgeDB, and of course if it will be implemented in say... a year?

I think sooner. We should release v2 in May, FTS can be a feature in v3 which will be released before the EOY.

**Comment by muhammadshaban** [comment]
Is there any news about this feature
Also, could you please update the roadmap with the latest status
https://edgedb.com/roadmap/

**Comment by williambarberjr** [comment]
> 

Any update on when full text search is likely to at least make the roadmap?

**Comment by elprans** [comment]
> Any update on when full text search is likely to at least make the roadmap? 

Support for FTS is coming in 3.0.  Please see the [RFC](https://github.com/edgedb/rfcs/blob/master/text/1015-full-text-search.rst) for details.

**Comment by williambarberjr** [comment]
> Support for FTS is coming in 3.0.  Please see the [RFC](https://github.com/edgedb/rfcs/blob/master/text/1015-full-text-search.rst) for details.

Great and thanks for sharing that link. Any idea what the current timeline looks like for the 3.0 release? A July 28th blog post about the 2.0 release mentioned 6 months as the target for the 3.0 release.

**Comment by elprans** [comment]
We should hit 3.0 feature freeze (and the first beta) sometime later this month or early Mar.

**Comment by TheNoim** [comment]
You guys should update the roadmap https://www.edgedb.com/roadmap I mean, everything "PLANNED FOR 1.X" is completely wrong.

**Comment by raddevon** [comment]
@TheNoim We agree and are in the process of updating it. We no longer link to the current iteration because it does not reflect our most current plans.

**Comment by williambarberjr** [comment]
This comment probably belongs in a discussion rather than an issue, but wanted to mention to @vpetrovykh that for what it's worth, my dream asks for full text search are vector embeddings and bm25, or bm25f. Yesterday Weaviate released an implementation that enables "hybrid search" with bm25f + dense vector embeddings search which can be done on a faceted search now as well (the faceted search feature alongside this is what was just released). 

More discussion of what hybrid search is (https://weaviate.io/blog/hybrid-search-explained) and how it's being implemented here: https://github.com/weaviate/weaviate/issues/2134

Not trying to be that guy that's expecting the world from an open source product but still wanted to contribute my thoughts. Unfortunately I'm closer to a useless product manager than a dev so I can't directly assist with implementing this, can only comment on the requirements I'm looking to meet for a search application that would also benefit from a graph database structure.

**Comment by beerose** [comment]
Hey all,

The full-text search feature [was released in 4.0](https://github.com/edgedb/edgedb/releases/tag/v4.0). I'm closing this issue, then.
