### ISSUE TITLE
Expose `VACUUM [FULL]` as an `administer` function

### ISSUE THREAD

**Issue by elprans** [edgedb/edgedb#6663]
`VACUUM` is useful for when autovacuum is not enough, and `VACUUM FULL` can be used to reclaim disk space after a wide-ranging update on a relation.

**Comment by AnsonHwang86** [comment]
I just encountered another similar case. My cloud used rate is about 87%, and I try to add fts to current schema.

something like this
```
   fts::with_options(
          .productTitle,
          language := fts::Language.eng,
          weight_category := fts::Weight.B
      )
```

Then `edgedb migration create`
next `edgedb migrate`

Due to the large data in that property(here is .productTitle), the storage is used up(100%). the migration fail and the database in that instance can't be accessed. It seem can't be rollback auto. I try to restart it using `edgedb instance restart` but no work. The error say `wsl` is not installed.

My suggest here is to see if can add a action on the cloud UI to let the user to restart the instance to clear cache.

(I have filed a support tick, my instance is working now, thanks.)
