### ISSUE TITLE
Issue with type casting of integers

### ISSUE THREAD

**Issue by jrycw** [edgedb/edgedb#6700]
- EdgeDB Version: 4.4+9974f3c
- EdgeDB CLI Version: 4.0.2+b26c502
- OS Version: Windows11

Steps to Reproduce:
1.  ok as expected.
```
tt:edgedb> insert MyNumber {number:= <int16>1234 };
{default::MyNumber {id: 1f0c2598-b2b5-11ee-bf5d-079f11515058}}
```
2.  failed as expected.
```
tt:edgedb> insert MyNumber {number:= <int32>1234 };
edgedb error: InvalidPropertyTargetError: invalid target for property 'number' of object type 'default::MyNumber': 'std::int32' (expecting 'std::int16')
```
3.  I expected to get an `InvalidPropertyTargetError` but successfully created a `MyNumber`.
```
tt:edgedb> insert MyNumber {number:= <int64>1234 };
{default::MyNumber {id: 22807242-b2b5-11ee-bf5d-d7154f6739e4}}

tt:edgedb> insert MyNumber {number:= 1234 };
{default::MyNumber {id: 257cc7f2-b2b5-11ee-bf5d-3f87384dd245}}
```

Schema:
```
module default {
    type MyNumber {
        number: int16;
    }
}
```

**Comment by Dhghomon** [comment]
I'm seeing the same behavior with floats too. If I create a `MyFloat` type with a `number: float64` or a `number: float32` it will accept a cast into the other float type without issues.

And one might think that this is an implicit cast if not for the `insert MyNumber {number:= <int32>1234 };` query you bring up that does fail.

**Comment by msullivan** [comment]
@vpetrovykh Could you look into this and see if there's anything that can be untangled?

Either both should work or both shouldn't.
Honestly probably both shouldn't work, but we might need to make both work instead.

**Comment by vpetrovykh** [comment]
There are a few things interacting here, in the casting system (see [casting table](https://docs.edgedb.com/database/reference/edgeql/casts#ref-eql-casts-table))

We have some general rules:
1) The operations should be "safe" or at least as safe as possible. Which means that things that can cause errors should not happen implicitly. This means that we generally don't want to allow mixing up types if they are "too different". So it's OK to write `1 + 2.3`, but not `1 + "2.3"` even though you could cast that string explicitly `1 + <float64>"2.3"`. This means that typically you can mix numerical types to some extent, but usually not any of the other types.
2) We generally want to allow mixing numerical types if we can cast them to whichever type has more precision. So it's always safe to upcast in this direction `int16` => `int32` => `int64`, but we can't assume that going in reverse direction is safe, so it needs an explicit cast. Similarly, we assume that you can go from `float32` to `float64`, but not in reverse without losing data. For the same reason we don't implicitly cast from "unlimited precision" numbers like `decimal` or `bigint` to any of the other numerical types. If you want that, you need an explicit cast.
3) Assignments are special, they often happen when a user is providing the values in a query directly as literals and not as typed parameters. So we wanted to make it more convenient to write `insert Foo{bar := 23, baz := "GREEN"}` even when the properties `bar` and `baz` are not `int64` and `str`, respectively, but `int16` and some custom `enum` (that has `GREEN` as a valid value). This means that because when you write a number without any type information you get either `int64` or `float64` and these types will appear all the time in _assignments_ to any of the numerical properties. So in order to make `inserts` less annoying for 99% of common cases we treat these two types as valid _during assignment_ (such as `insert` or `update`) for all numerical types and we will cast them implicitly.

All of this means that in an insert you can assign 1234 to an `int16` property, but not `<int32>1234` to the same property.
On the other hand since we only have two float types and one of them is the default literal type you can assign that default literal to a `float32` property as well.
