### ISSUE TITLE
graphql: unknown type error

### ISSUE THREAD

**Issue by 1st1** [edgedb/edgedb#675]
Here's the error we report when a user queries an unknown type:

```
{
  "errors": [
    {
      "message": "QueryError: Cannot query field \"Movie\" on type \"Query\".",
      "locations": [
        {
          "line": 2,
          "column": 5
        }
      ]
    }
  ]
}
```

Instead of this rather obscure message we should simply say something like this: `Unknown type "Movie"`

**Comment by vpetrovykh** [comment]
This error message is generated by the `graphql` module. Of course, we can intercept it and change it, but there are a few things to consider:
1) This error message is identical in structure if you try to access an unknown nested field, except, of course, the type will be something other than "Query". If the name is slightly misspelled the error message will even offer a hint of what the correct spelling could be.
2) Strictly speaking this is perfectly reasonable GraphQL error. Remember that all top-level queries are *fields* of the type `Query` (and once we allow mutations or subscriptions then it may also be a field of type `Mutation` or `Subscription`). That's just the canonical GraphQL structure. Since we know and control all our types we can at least distinguish the particular case when the field is on a top-level Query.
3) Saying that it is an "Unknown type" really means "Unknown mapped EdgeDB type". The wording is a little awkward since technically it can also be a view, not just a type. So the message then would be more like "Unknown mapped EdgeDB type or view".
4) In the current GraphQL implementation we only have one field per type/view matching the name of the EdgeDB concept exactly. However, it is a very popular pattern in other GraphQL implementations to have one field "getFoo" and another "getAllFoo" per each reflected type "Foo". This roughly corresponds to `fetchone` and `fetchall` so it's not unreasonable that we may decide to also have something similar. This means that we probably should keep the original error message as it refers to the specific GraphQL field.

From the above, it appears that the updated error message would be something like:
` "QueryError: Cannot query field \"Movie\" on type \"Query\". There's no corresponding type or view \"Movie\" exposed in EdgeDB."`

With possible future variations of:
` "QueryError: Cannot query field \"fetchone_Movie\" on type \"Query\". There's no corresponding type or view \"Movie\" exposed in EdgeDB."`

It's a good idea to suggest checking the GraphQL port configuration to make sure which database this port is actually connected to. The most likely cause of not having the expected top-level fields is that the user is connecting to the wrong port or exposed the wrong database.
