### ISSUE TITLE
Nested bulk queries with idempotent/select-or-insert logic

### ISSUE THREAD

**Issue by thedeadliestcatch** [edgedb/edgedb#6790]
I am preparing a reduced test-case for this issue, but at the moment I can summarize the situation:

- Assume a simple schema with objects Foo, Bar, BarAssociationWithFoo.
- We are inserting an amount of Foo objects, from an input dict (assuming Python library here for now).
- The Foo objects have a set of fields and a set of Bar objects (as a list of -named- tuples).
- During bulk insertion of the Foo objects, a nested query is leverage to iterate foo_list passed to the query as an argument.
- Ideally, each Foo object should be either inserted or selected if already present (based on an existent uniqueness constraint).

The expected result would be the idempotent insertion-or-selection of a Foo object with the nested idempotent insertion-or-selection of several (or none) Bar objects linked to it.

An additional 'want' would be the ability to use an associative type BarAssociationWithFoo in the nested query.

I need to collect my notes, but during testing, I observed one case where the state of the query is inconsistent.

For the purpose of the test-case, the schema would be like so:

```esdl
scalar type DataItemType extending enum< 
    'phone'
>;

type BaseData {
}

 type Subscriber extending BaseData {
    required property first_name -> str;
    property middle_name -> str;
    required property last_name -> str;

    # Composite uniqueness constraint
    constraint exclusive on ((.first_name, .middle_name, .last_name));

    # Computed property for the full name
    property full_name -> str {
        using (
            (.first_name IF .first_name != '' ELSE '') ++ 
            (' ' ++ .middle_name IF .middle_name != '' ELSE '') ++
            (' ' ++ .last_name IF .last_name != '' ELSE '')
        );
    }

    # Property for case-insensitive uniqueness
    property name_lower -> str {
        using (str_lower(.full_name));
        constraint exclusive;
    }
    
    multi link phone_numbers -> PhoneNumberAssociation;
}

type PhoneNumber {
    property original_number -> str;         # The actual phone number
    required property number -> str;         # The actual phone number
    property area_code -> int16;
    property country_code -> int16;            # Optional country code

    multi link associations -> PhoneNumberAssociation;

    required property computed -> str {
        default := .full_phone_number;
        constraint exclusive; 
    }

    # Computed property for the full phone number
    property full_phone_number -> str {
        using (
            (<str>.country_code ++ '-' IF <str>.country_code != '' ELSE '') ++
            (<str>.area_code ++ '-' IF <str>.area_code != '' ELSE '') ++
            (.number IF .number != '' ELSE '')
        );
    }

    overloaded required property item_type -> DataItemType {
        default := 'phone';
    }
}

type DataItemAssociation {
    required link entity -> Entity;
}


type PhoneNumberAssociation extending DataItemAssociation {
    required link phone -> PhoneNumber;
    constraint exclusive on ((.entity, .phone));
}

```

The following query results in the inconsistent state I mentioned earlier:
  
```edgeql  
with new_subscriber := (
    insert Subscriber {
        first_name := <str>$first_name,
        middle_name := <str>$middle_name,
        last_name := <str>$last_name,
    }
    unless conflict on .name_lower
    else (select Subscriber)
)
update Subscriber set
{
    phone_numbers := (
        WITH phone_data := <optional array <tuple <country_code: int16, area_code: int16, number: str, orig_number: str>>> $phone_numbers
        FOR phone_item IN array_unpack(phone_data) union (
            INSERT PhoneNumberAssociation {
                    subscriber := new_subscriber,
                    phone := (
                        INSERT PhoneNumber {
                            country_code := phone_item.country_code,
                            area_code := phone_item.area_code,
                            number := phone_item.number,
                            original_number := phone_item.orig_number
                        } unless conflict on (.computed) else PhoneNumber
                    )
            } unless conflict on (.subscriber, .phone) else PhoneNumberAssociation
        )
    )
    )
 ```
    
Using a test harness I observed that PhoneNumberAssociation objects are not created, and the PhoneNumber insertions are not actually happening for the full set. It seems the state of the nested query becomes corrupted.

**Comment by raddevon** [comment]
I was able to apply the schema by creating an empty `Entity` type and by removing `overloaded` from the `PhoneNumber` type's `item_type` property. That still left me with a couple of spots where the schema and the query were not in agreement though:
- you have assigned a `subscriber` property of `PhoneNumberAssociation` in your query and checked for conflict on it, but it doesn't exist in the schema
-`PhoneNumberAssociation` requires an `entity` link, but it isn't assigned in the query.

A few things I notice about the query:

- I think there's a minor syntax error in the query. I can't make it run as it is here. I needed to change the final close paren to a closing curly bracket instead.
- `update Subscriber`- This will update all existing `Subscriber` objects with the same phone number data. Is this your intent? If your intent is instead to update only the single new or existing subscriber, this query will not work. This query would not update a subscriber being inserted since that object is not in the database when the query is run, so if your goal is to update either the recently inserted or existing selected user `new_subscriber` with the `update` portion of this query, you'll only accomplish that in cases where the subscriber already existed, but you'll also update every other existing subscriber with the same phone numbers. `Subscriber` in this context refers to the type since it is in a different scope than your use of subscriber earlier.
- You cannot update an object on the same query it is inserted. If you need to update on the insert, you would want to instead just insert with whatever data you would have updated with. You will only want to update if the `Subscriber` object already exists. I haven't tried testing this yet, but I think it might be a workable alternative for you with a tweak or two:

```edgeql
with phone_data := <optional array <tuple <country_code: int16, area_code: int16, number: str, orig_number: str>>> $phone_numbers,
phone_numbers := (
    FOR phone_item IN array_unpack(phone_data) union (
        INSERT PhoneNumberAssociation {
            phone := (
                INSERT PhoneNumber {
                    country_code := phone_item.country_code,
                    area_code := phone_item.area_code,
                    number := phone_item.number,
                    original_number := phone_item.orig_number
                } unless conflict on (.computed) else PhoneNumber
            )
        } unless conflict on (.phone) else PhoneNumberAssociation
    )
),
subscriber := (
    insert Subscriber {
        first_name := <str>$first_name,
        middle_name := <str>$middle_name,
        last_name := <str>$last_name,
        phone_numbers := phone_numbers
    }
    unless conflict on .name_lower
    else (select Subscriber)
),
subscriber_exists := (subscriber in Subscriber)
select (update subscriber set
{
    phone_numbers := phone_numbers
}) if subscriber_exists else (select subscriber);
```

Note that, if you have conflicting phone numbers or phone number associations that would be inserted in this query (i.e., the original and conflicting inserts would both happen in this query), `unless conflict` will not help with those as it only works to prevent conflicts with objects that have already been inserted. If you think that could happen here, you'll want to make sure the objects you're inserting on this query are distinct.

**Comment by raddevon** [comment]
Closing this for now, but feel free to re-open if you need anything else.
