### ISSUE TITLE
Mysterious test hangs in `start_edgedb_server`

### ISSUE THREAD

**Issue by msullivan** [edgedb/edgedb#6799]
Fantix and I have both been able to replicate this, at least sometimes.
`edb test -j32 -k test_server_adjacent -k test_server_proto  -v` fairly consistently has a hang on @fantix's machine.

I've managed to reproduce it with `taskset -c 0-15 edb test -j32 -k test_server_adjacent -k test_server_proto  -v` on my test machine, but not consistently.

I discovered this while testing https://github.com/edgedb/edgedb/pull/6782, and with https://github.com/edgedb/edgedb/pull/6782 there seemed to also be knock-on effects where some other DROP DATABASE commands hung, which needs to be tracked down.

**Comment by fantix** [comment]
Looks like the hanging happens during server start, when the pool failed to complete a connection acquisition when it's exhausted by concurrent database (early) introspection due to test database clones, like shown in my debug:

```
413955 EARLY INTROSPECT __edgedbsys__
413955 EARLY INTROSPECT edgedb
413955 EARLY INTROSPECT serverprotoconcurrentddl
413955 EARLY INTROSPECT serverconfig
413955 EARLY INTROSPECT serverproto
413955 EARLY INTROSPECT serverprotoddlpropagation
413955 EARLY INTROSPECT serverprotoconcurrentglobalddl
413955 EARLY INTROSPECT serverprotoddl
413955 EARLY INTROSPECT serverprotomigration
413955 EARLY INTROSPECT serverproto_413755
413955 EARLY INTROSPECT serverproto_413753
413955 EARLY INTROSPECT serverprotoddl_413751
413955 EARLY INTROSPECT serverprotoddl_413752
413955 EARLY INTROSPECT serverprotoddl_413745
413955 EARLY INTROSPECT serverprotoddlpropagation_413749
413955 EARLY INTROSPECT serverprotoddlpropagation_413748
413955 EARLY INTROSPECT serverprotoddlpropagation_413747
413955 EARLY INTROSPECT serverprotomigration_413750
```

(18 concurrent requests on the pool with a size of 10)

In detail, the pool had to steal a connection from other blocks, but the async task was never resumed for some reason.

@msullivan @1st1 With databases transiting to branches, is it still necessary to maintain a connection pool that mostly deals with the case when many databases/branches are competing for a limited number of connections?
