### ISSUE TITLE
`assert_single` feels like a misnomer...

### ISSUE THREAD

**Issue by jsimonlane** [edgedb/edgedb#6920]
The docs state it can be 0 or 1.

I feel like assert_single means (at least to me), it should be one and only one.

Is there some set theory I'm missing here?

https://www.edgedb.com/docs/stdlib/set#function::std::assert_single

**Comment by raddevon** [comment]
I didn't have the historical context for this one, so I asked around. Seems that, although the name is a bit counter-intuitive, `single` here is intended to mirror `single` in the schema which defines an upper bound rather than a lower bound. This was conceived as an alternative to `limit 1` which is also only an upper bound.

You may already be aware, but it's possible to achieve "assert this returns exactly one" by combining `assert_single` with `assert_exists` like this:

```edgeql
select assert_exists(assert_single({1}));
```
☝️ will result in `{1}`.

```edgeql
select assert_exists(assert_single({1,2}));
```
☝️ will result in `edgedb error: CardinalityViolationError: assert_single violation: more than one element returned by an expression`

```edgeql
select assert_exists(assert_single(<int16>{}));
```
☝️ will result in `edgedb error: CardinalityViolationError: assert_exists violation: expression returned an empty set`

We will consider adding something like `assert_exists_single` which will make the DX for this a bit nicer. I'll close this but open another ticket to capture this idea.
