### ISSUE TITLE
Aliasing the PKCE Parameter "challenge" for RFC Alignment

### ISSUE THREAD

**Issue by Crain-32** [edgedb/edgedb#7026]
Currently the PKCE flow for the Auth Module expects the following parameter, `challenge`.

The [PKCE RFC's](https://datatracker.ietf.org/doc/html/rfc7636#section-6.1) Parameter for this is `code_challenge`.

Given the amount of code that likely targets `challenge`, I'd assume it would be best to let both `challenge` and `code_challenge` work for a period of time, with `challenge` taking precedence for the foreseeable future.

This would allow for easier integrations with Spring Security for example, as it currently supports EdgeDB Auth until you hit login.

Documentation on if EdgeDB supports the `code_challenge_method` would be good as well.

**Comment by scotttrinh** [comment]
@Crain-32 

Thanks for the feedback! Yeah, I think we can add an alias for `code_challenge` and `code_verifier` to conform to the RFC. We implement PKCE outside of OAuth, so didn't feel beholden to the original RFC since EdgeDB Auth is not itself an OAuth authorization flow, but if it makes it easier to integrate existing tooling, I'm 100% down.

> Documentation on if EdgeDB supports the `code_challenge_method` would be good as well.

We don't currently support it since we _require_ SHA256 and we're breaking with the RFC here by not assuming `plain` by default here. I'd be happy to add the parameter, with the caveat that we would reject if you ask for `plain`, so it would in essence be superfluous (missing would default to `S256` and present would only allow `S256`), which is not compliant with the RFC. Any thoughts on that?

**Comment by Crain-32** [comment]
Hey @scotttrinh!

Integration with `code_challenge_method` isn't really something I'm partial towards, but it should be nice to state that SHA256 is a hard requirement. Currently the documentation only says
> Take this verifier string, hash it with SHA256, and then base64url encode the resulting string. This new string is called the challenge.

I think just a minor adjustment to the declaration of supporting PKCE would be a simple way to tell that.

> We secure authentication tokens and other sensitive data by using PKCE (Proof Key of Code Exchange), and only support the usage of SHA256.

**Comment by scotttrinh** [comment]
@Crain-32 Great, thanks for the feedback and direction there. Should be a pretty quick fix.
