### ISSUE TITLE
Insert query fails silently after upgrading to 4.6

### ISSUE THREAD

**Issue by lsdch** [edgedb/edgedb#7067]
- EdgeDB Version: 4.6+0632dff
- EdgeDB CLI Version: 4.1.0+03ae624
- OS Version: Linux Mint 21.3

Steps to Reproduce:

1. Migrate the provided schema on an EdgeDB 4.6 instance
2. Run query:
```edgeql
select (insert people::Person {
  first_name:= "Test",
  last_name:= "TEST"
}) { * }
# Returns an empty set
```
Running only the `insert` statement also return an empty set.  
Checking the database content confirms that the item was not inserted.
Insertion of other object types seems to work, although I only tested a few of them.

Everything works as expected on v4.5.

Schema:

- Schema definition files: https://gist.github.com/lsdch/22ea6f875e7df4481e73da26dd0ca891
- Migration file: https://gist.github.com/lsdch/cca2800c7ab63f431d1fe3ab2d818298

**Comment by msullivan** [comment]
Thanks for the report!

This issue is a knock-on effect of https://github.com/edgedb/edgedb/issues/7061.

Because the cardinality of the current_user global gets inferred incorrectly in queries, we perform some optimizations that are unsound when dealing with something of optional cardinality.

This will be fixed in 4.7 by reverting #6613 and in 5.x by https://github.com/edgedb/edgedb/pull/7062
