### ISSUE TITLE
Support writes in the SQL adapter

### ISSUE THREAD

**Issue by msullivan** [edgedb/edgedb#7294]
The trickiness here is in supporting all of the various special edgeqlisms that affect writes:
 * Rewrites
 * Triggers
 * Access policies? (We'd probably want that to work on reads also -- which is doable)
 * Cross-table exclusive constraints
 * Built-in foreign keys
 * `required multi` pointers

My theory for how to implement this, which is not fully formed, is to turn the DML operations in the SQL queries into not-DML CTEs, and then basically use the edgeql compiler to compile edgeql DML that is rigged up to take those CTEs as input. (Using a generalization of external rvars, probably).
That should then let all our hooks operate.

We'd also probably need to compile in assertions that link uuids actually map to a real object.

There are still a bunch of questions, especially around link tables, but I think this *should* be workable.

**Comment by msullivan** [comment]
One thing we need to figure out an answer for is how to specify global variables to the SQL protocol. The *simplest* approach would be to expose it as a config value where you specify JSON encoded globals, but we might want something smarter.

**Comment by aljazerzen** [comment]
My strategy is to first implement INSERT and then DELETE and UPDATE with reusing code blocks / functions from the INSERT implementation.

Todo for INSERT:
- [ ] multiple values (properly set for iterator),
- [ ] links (`INSERT "Movie" (director_id) VALUES ("61e477c9-5ef7-419f-804c-86f5f1a2d78e"::uuid)`),
- [ ] make sure that triggers run at the end of the top-level-query, not at the end of current DML query,
- [ ] DML in CTEs (push generated CTEs one level up so they are always top-level, and reject DML in non-top-level CTEs)
- [ ] reuse alias generator between compiler invocations to prevent name conflicts,
- [ ] RETURNING values,

**Comment by aljazerzen** [comment]
Modified rows in query result:

When INSERT is the top-level statement in the query, Postgres response will contain a [CommandComplete (B)](https://www.postgresql.org/docs/current/protocol-message-formats.html#PROTOCOL-MESSAGE-FORMATS-COMMANDCOMPLETE) with tag `INSERT oid rows`, where `oid` is always 0 and `rows` is number of inserted rows.

Because we compile INSERT into SELECT with many CTEs, INSERT is not top-level statement in the query, which means that the postgres response will not contain the appropriate tag.

Also, if the INSERT did not specify RETURNING columns, there should be no result. Again, because we compile to SELECT with CTEs, that will produce a result, with no columns.

To solve this, we will modify the server IO code that proxies compiled SQL requests to Postgres:
- compiler will detects presence of a top-level INSERT,
- when there is INSERT, server-io will count the number of rows being returned (even if there is 0 columns)
- it will then construct appropriate CommandComplete tag with the number of rows in result, which should always match the number of rows inserted,
- if the insert did not have RETURNING clause, it will also discard the result relation.

**Comment by aljazerzen** [comment]
More on modified rows:

When user does not specify RETURNING clause and modifies many many rows, current implementation will return many-many empty rows to the edgedb server process only for them to be counted and discarded.

A better way would be to inject a `COUNT(*)` into the top-level SELECT when RETURNING is not specified, and then catching the resulting row and passing that data into CommandComplete message.

This means that we have two ways of providing the modified row count, two implementations that need maintenance, but very low impact on performance.

**Comment by aljazerzen** [comment]
TODO Delete:
- [x] DELETE FROM object table,
- [ ] DELETE FROM multi-link table,
- [ ] DELETE FROM single-link with properties table,
- [ ] DELETE FROM multi-property table,
- [x] WHERE, USING
- [x] RETURNING & CommandComplete tag
- [ ] ~WHERE CURRENT OF~
- [ ] WITH ... DELETE FROM

**Comment by aljazerzen** [comment]
TODO:
- figure out what to do about INSERT/DELETE/UPDATE ONLY
