### ISSUE TITLE
Captcha providers for built-in auth UI

### ISSUE THREAD

**Issue by pspsdev** [edgedb/edgedb#7341]
Currently if you want to add captcha you would need to implement your own UI for auth. Add integration with most popular captcha providers e.g cloudflare turnstile, hcaptcha

**Comment by scotttrinh** [comment]
Thanks for the recommendation! At the moment, we'd like to keep the built-in UI mostly focused on quick iteration on simple projects since we feel like most projects of any real size want to build out a more customized UI. In the short term, we're likely to make it _easier_ to build a custom UI rather than adding more configuration and flexibility to the built-in UI.

I'm going to close this as not planned for now, but keep an eye out for updates that make implementing your own custom UI easier.
