### ISSUE TITLE
select exists ( not working inside function

### ISSUE THREAD

**Issue by nitulkukadia** [edgedb/edgedb#7837]
- EdgeDB Version: {'4.7+5f83595'}
- EdgeDB CLI Version: EdgeDB CLI 4.1.0+c3b6bc7
- OS Version: Running with docker image -> edgedb:4.7 on macOD Sonoma Version 14.6.1

Steps to Reproduce:

1. execute : select exists (<std::str>{}); this will return {false}
2. execute select isPresent(<std::str>{}); this will return {} instead of {false}

Schema:
module default {
      function isPresent(s: std::str) ->  std::bool using (
select  EXISTS (s)
    );
 
};

**Comment by msullivan** [comment]
This is expected behavior. If you call `isPresent(<str>{})`, `isPresent` will be called for each member of its input set -- namely all zero of them`, and so return `{}`.

If you declare the parameter to the function as `OPTIONAL`, then it will get called with an empty set, and you'll get the behavior you want.

**Comment by nitulkukadia** [comment]
yes adding an OPTIONAL paremeter is working, Thanks.
