### ISSUE TITLE
Module has no attribute "EdgeQLError"

### ISSUE THREAD

**Issue by ambv** [edgedb/edgedb#784]
Reported by mypy 0.740 on be705ce77d6a5f6d66a94691b4f7d0fb555b34b0 (possibly also true before):

edb/edgeql/compiler/clauses.py:110: error: Module has no attribute "EdgeQLError"
edb/edgeql/compiler/clauses.py:117: error: Module has no attribute "EdgeQLError"

**Comment by elprans** [comment]
@vpetrovykh We need a test that covers the branches in question.

**Comment by vpetrovykh** [comment]
Actually, under the current type system it should be impossible to reach those errors, because right now *every* type is orderable and thus can be used in an `ORDER BY` clause. It would take a new [scalar] type (not merely extending an existing one) that has some weird `<` or doesn't have one at all to trigger either one of these errors.

It's actually not easy to come up with a scalar that would truly be unorderable yet still useful. Also, if something is unorderable, but can be cast into a string it simply becomes a weird hoop for the users to jump through if we insist on making the scalar itself unorderable (we've had this discussion when considering whether UUIDs should be orderable).

**Comment by 1st1** [comment]
Alright, we can close this then. Typos in class names will be checked by mypy soon.
