### ISSUE TITLE
Consider removing `local_datetime`

### ISSUE THREAD

**Issue by tailhook** [edgedb/edgedb#875]
# Idea

Make a single datatype for a timestamp which is basically UTC datetime.

# Motivation

1. There are very little use cases (if any) of the type
2. It's a source of lots of errors
3. If you really want it, think twice and use two fields for date and time (i.e. date when alarm first started and time when it should ring for a recurring alarm, instead of cobining the two)

# What other databases are doing?

Terms:
* *naive* -- timestamp without timezone specified (for example `2019-11-25 22:10:42` if written as string)
* unix timestamp -- specific representation of datetime in seconds since the unix epoch (epoch is in UTC so the whole value doesn't depend on the time zone)
* UTC-normalized timestamp -- means datetime stored as UTC internally being it unix timestamp or timestamp at UTC

**Databases:**

* **PostgreSQL** has `TIMESTAMP` which is documented to be UTC but accepts a *naive* timestamp as an input, so easy to misuse. And `TIMESTAMPTZ` which accepts any timezone offset as input and converts to UTC timestamp internally. Converts to client session time on output.
*  **MySQL** has `TIMESTAMP` which accepts a *naive* timestamp in local time and does autoconversion to UTC for storage. `DATETIME` is just a *naive* timestamp without conversion
* **VoltDB** uses UTC-normalized `TIMESTAMP`. As long as I understand it has Java API and it's hard to mess with timezones (because it's converted from java.date.Date that is basically a unix timestamp)
* **MongoDB** has UTC-normalized timestamp named `Date` (as far as I understand when converting to/from a string they only accept `Z`-suffixed format `2019-11-25T22:10:42Z`). *Name probably inherits JavaScript type name*
* **Clickhouse** use *naive* format that is converted to/from local time, named `DateTime` (basically like `TIMESTAMP` in mysql)
* **FoundationDB** (in document layer) basically supports MongoDB semantics
* **RethinkDB** actually store timestamp + timezone, named `time`
* **Cassandra** uses UTC-normalized `timestamp` and auto-converts to timezone in some clients
* **Redis** has no datatype for storing datetimes but uses unix timestamp (in seconds) in commands like `EXPIREAT`

**Conclusions:**
1. Except in PostgreSQL and MySQL every database has a single datetime type (most of them don't have separate date or time, though)
2. Whereas PostgreSQL and MySQL looks like were trying to fix a mistake, that's why they added a type, not because two types needed
3. Timestamp means different things in different databases so it's okay to give it our own meaning (i.e. rename datetime -> timestamp)

**Update:** added cassandra

**Comment by vpetrovykh** [comment]
Cool, now please implement a recurring alarm with arbitrary periodicity, say every 13 days, 5 days, or 36 hours.

**Comment by vpetrovykh** [comment]
Think about it as an alarm for shift work, for example.

**Comment by tailhook** [comment]
> Consider implementing a recurring alarm with arbitrary periodicity, say every 13 days, 5 days, or 36 hours.

Off the top of my head:
```
type Alarm {
  property last_trigger -> local_date;
  property alarm_time -> local_time;
  property interval_days -> int32;
}
```
I don't even understand how `local_datetime` helps:
```
type Alarm {
  property last_trigger -> local_datetime;
  property interval_days -> int32;
}
```
Looks less clear, because the date of the last trigger is something system updates. And time is something user-specified once and it's read-only until they change it next time

This works for the whole-day periods. For less than day periods, the only sane thing is counting hours from timestamp. Or encoding more user-specific semantics here (i.e. how to account DST changes specifically).

**Comment by elprans** [comment]
@tailhook The crucial detail you're missing is [`std::duration`](https://edgedb.com/docs/datamodel/scalars/datetime#type::std::duration), which works with `std::local_datetime`, so here's how this could be implemented:

```
type Alarm {
  property next_trigger -> local_datetime;
  property interval -> duration;
}
```

```
UPDATE Alarm SET { next_trigger := .next_trigger + .interval };
```

If you separate `local_datetime` into a `date` and `time` tuple, this would no longer work.

**Comment by vpetrovykh** [comment]
> This works for the whole-day periods. For less than day periods, the only sane thing is counting hours from timestamp.

If I work shifts with periodicity of 36 hours (basically alternating day and night shifts) what that means is that my alarm is set for 7AM and 7PM in my local time, disregarding time zones, daylight saving time, etc. In fact, if you work with timestamp you'll be wrong on the day when time shifts by 1 hour in spring and fall. `local_datetime` allows me to pick a starting point and perform arithmetic on it by adding `<duration>"36 h"`. With 2 values this becomes complicated since you now need to count rollovers. 

Also, effectively forcing every user to implement their own `local_time` by combining `date` and `time` is likely to generate more errors and less reusable code. It's the whole point of the standard library that it should provide tools for common concepts.

**Comment by tailhook** [comment]
@elprans 
> The crucial detail you're missing is std::duration, which works with std::local_datetime

That magic duration where `1 day` isn't the same as `24 hours` is another item on my "to discuss" list. Python's timedelta, Rust's Duration, Go's Duration are all have the shared semantics and don't have such oddity. So it's confusing. But let's keep that discussion in another thread...

-----

>```
>UPDATE Alarm SET { next_trigger := .next_trigger + .interval };
>```

The way it gives you the right result is just a coincidence (or maybe convenience). But as I've already said there are two different things: `time` specified by the user that you don't want your code to be accidentally changed by adding `24 hours` instead of `1 day` to the timestamp in the middle of DST change (like example below). And last trigger date (which I actually would consider storing as full timestamp).

@vpetrovykh 
> If I work shifts with periodicity of 36 hours (basically alternating day and night shifts) what that means is that my alarm is set for 7AM and 7PM in my local time

You nailed it! Two alarms with 3 day period.

Just imagine your timer setup dialog where every other day when you open settings of your event and they are different (not just next event date is different, but settings).

> In fact, if you work with timestamp you'll be wrong on the day when time shifts by 1 hour in spring and fall

That's specifically what I'm aware of. That's why I said, that application needs encoding specific semantics. Contrary to your example: if a battery needs to be changed every 36 hours, you can damage a system by having it stuck for 37 hours.

*A bit offtopic: There was a recent tweet which said that not all billing systems account that on DST change you would work +1 extra hour. And this is what this math essentially encourages to do (it's okay if it's just alarm, but we don't model types for only one use case).*

At the end of the day, if you're making a calendar app you can't rely on a database to make all decisions for you. You must be aware of semantics. And you must make business logic for your application according to that.

**Comment by elprans** [comment]
@tailhook 

> That magic duration where `1 day` isn't the same as `24 hours`

There is no such magic in the UTC timezone, and that's the only thing we support.

> You nailed it! Two alarms with 3 day period.

Intervals are not limited to ones that can be decomposed into a round number of days, this was just an example. Please extrapolate this to a general concept.

> You must be aware of semantics. And you must make business logic for your application according to that.

Um, this is a bit of a straw man, we're not arguing that. `local_datetime` and `duration` are just tools that let you express your data and logic in a cleaner way, you are free to use them or not.  I really don't see how removing these and forcing the users to juggle `(date, time)` tuples and performing manual, error-prone time arithmetic is going to make anybody's life easier.  

You are trying to paint `local_datetime` as evil, but you haven't presented a clear argument as to why. The overview of other databases is useful, but isn't an argument in itself, since you've basically included the entire spectrum of expressive capability (Redis and Mongo are not comparable to Postgres by a long shot).

**Comment by tailhook** [comment]
Okay as one datapoint [iCalendar](https://tools.ietf.org/html/rfc5545) does have the notion of "local datetime" they also call it "floating datetime". But here is the controversy:
1. One might argue that to store iCalendar data in edgedb you need `local_datetime`
2. On the other hand, iCalendar also has "datetime with specific timezone" type, which can only be stored as a tuple `(local_datetime, timezone)`

The position is that backs (1) and also ignores (2) is a bit hypocritical in some sense.

**Comment by 1st1** [comment]
Alright, I've given this some thought in light of the discussion of this topic on our team call today.  Here's the TL;DR part:

* I'm **-1** on removing the `local_datetime` datatype.
* I'm **+1** to rename `local_datetime`, `local_time`, and `local_date` to `clock_datetime`, `clock_time`, and `clock_date`.

At this point I think we should wind down this discussion and focus on shipping Alpha 2.

---

Paul's main motivation to remove the `local_datetime` type falls down to:

1. Users can be confused and pick the wrong datatype for storing their date/time data.
2. If the use case for the datatype is too marginal we should not have it. Having "nice to haves" increases maintenance costs and mental overhead.
3. Other databases do not have naive date/time type.
4. Some programming languages (including recent ones) don't have naive date/time type.

*Regarding (1):* I believe this should be addressed by providing a better **documentation and appropriate naming**. I admit that the current "local" term can be confusing. Since in all of our discussions we always say that "local time" is about "clock time" I think we should just rename our naive types to use the word "clock".

*Regarding (2):* First, I don't think that the use case is marginal. We did use a "reminders" app as an example for when some developers would prefer to use `local_datetime`. But it goes deeper than that; notifications, schedules, do not disturb times, alarms: they all conceptually operate in local time to the user. I can totally see our own cloud offering having user settings for when we should send our users performance reports or analytics. Such settings are location independent, i.e. it does not matter where the user is, did a DST transition happen or not—a user just wants to see their report on Wednesday at 10am local time.

Paul argues that for a marginal use case like that a tuple of  `(local_date, local_time)` can be used. True, but then there is no way our users can perform date/time arithmetic on such values. How would a user shift all their local date/time values 10 minutes to the future? Or how do you express "send me a message 10 minutes prior to [this local date/time]"? How would you implement school schedule app without using local date/time? Saying all these examples are "not realistic" or "not relevant" does not cut it, sorry. And here we arrive to another topic: how do we want to design EdgeDB. What features should make it and what should not?

In my opinion, it's finding the balance between *understanding if a feature addresses a marginal or a popular use case*, and between *whether it is possible to emulate the feature* if a user is facing that marginal use case. And for `local_datetime` the answer is simple: implementing date/time arithmetic for a `(local_date, local_time)` tuple would move our users to the world of pain.  They wouldn't be able to use `std::duration`; they would either have to implement their custom date/time arithmetic via EdgeQL functions or to fetch the data and perform the calculation on the client side. But what if a user wants to update millions of values? All of them? This quickly becomes impractical.

If we want to be fanatical about this we can also drop `std::local_date` and `std::local_time` —they can also be easily implemented with a simple named tuple. And probably we don't want `std::duration` at that point. Would that be convenient? Well, for some users it wouldn't matter, but some would just continue using PostgreSQL because it offers all these features and EdgeDB would be just inferior to it.

We want EdgeDB and EdgeQL to be feature rich so that people solve less of data-related mundane problems on the client side. So let's continue doing that.

Further, I don't believe that maintaining  `std::local_datetime`  would require any significant effort. 

*Regarding (3):* this is a rather weak point as many databases nowadays are treated as dumb data stores. Little effort, if any, goes into designing good standard libraries, data types, and query languages. Naturally our philosophy is quite different from theirs and this is what separates EdgeDB from the competition.

*Regarding (4):* this doesn't really matter in this context. When you are dealing with a programming language it is easy to just install a third-party library for any missing functionality. Databases are different—it's not easy to install an extension in your hosted DB. Building useful date/time arithmetic abstractions for a `(local_date, local_time)` would be problematic even in EdgeDB.

---

At the very least I'm grateful to Paul for highlighting the fact that our current naming is non-obvious.  "local" can be ambiguous to users, and "naive" or "clock" prefix would read way better.

I think we should rename `std::local_` types to `std::naive_` or `std::clock_`. Either name would work fine IMO.

I'm **-1** on renaming `std::datetime` to `std::timestamp`. The key problem is that the `timestamp` type in Postgres is a direct opposite to our `std::datetime`. Given that EdgeDB is based on Postgres I can imagine that a lot of users would be confused and would be looking for the `std::timestamptz` type spending time and asking questions on StackOverflow.

**Comment by tailhook** [comment]
I'm kinda close to agree... But can we temporarily hide all `local_` types behind a feature gate for alpha 2 and postpone it to alpha 3? I think hiding is trivial. And I don't think these types are what will stop people experimenting with the alpha-stage database.

The issue why I think it could be hidden is, I'd like to make more though on it like:
* Maybe we just want to make the types namespaced `std::calendar::date` or `std::local::whatever`, that would make it clear why to use those types, and also advertize better that we explicitly have a bunch of stuff supporting the calendar-like functionality in applications
* And if we are going to support rich kind of functionality we might also want `std::calendar::datetime_with_timezone` type which also has a niche (but we need to figure out how hard is to implement that in postgres).

**Comment by vpetrovykh** [comment]
> But can we temporarily hide all local_ types behind a feature gate for alpha 2 and postpone it to alpha 3?

The `local_date` and `local_time` are pretty uncontroversial types with clear use cases, hiding them would be overkill.

**Comment by tailhook** [comment]
> The local_date and local_time are pretty uncontroversial types with clear use cases, hiding them would be overkill.

Yes, but they are niche-enough that can be in a namespace. And hiding them now is important just to make sure we have time to figure out if we want namespaces other than `std`.

**Comment by elprans** [comment]
FWIW, we already have more than one namespace in the standard library (aside from `std`): https://github.com/edgedb/edgedb/tree/master/edb/lib

**Comment by tailhook** [comment]
Decided to move it into a namespace #902
