### ISSUE TITLE
Hasura and Dgraph

### ISSUE THREAD

**Issue by lishine** [edgedb/edgedb#950]
What is the reason to do something already implemented in Hasura.
And what is the difference to Dgraph.
Or to Faunadb

**Comment by lishine** [comment]
How edgedb compares in performance to dgraph? Here is the problem of multifetching with graph on top of traditional db, in dgraph blog,  and they say that problem does not exist with dgraph.
https://blog.dgraph.io/post/building-native-graphql-database-dgraph/
![Screenshot_2019-12-07-14-47-49-939_com android chrome](https://user-images.githubusercontent.com/6741645/70374943-2d116d80-1901-11ea-9a18-fbf60ca4aebe.jpg)

**Comment by elprans** [comment]
Hi @lishine.

> What is the reason to do something already implemented in Hasura.
> And what is the difference to Dgraph.

Hasura is, entirely, a GraphQL API proxy on top of Postgres that is mostly oriented to be used in relatively simple client apps (predominantly JavaScript and mobile), or as part of some larger GraphQL system.

Dgraph is a graph database, like Neo4j, and is primarily oriented toward working with sparse data that does not have a strictly defined schema.

In contrast to Hasura and Dgraph, EdgeDB replaces traditional relational and document databases with a modernized, more capable database framework, which includes not only the database server itself, but also efficient and idiomatic integration into backend application languages.

Unlike Hasura, Dgraph and FaunaDB, EdgeDB implements a vastly more powerful query language: EdgeQL, which is designed to be more efficient and productive than SQL in many workloads, but especially in application development.  

GraphQL in EdgeDB is implemented on top of EdgeQL and the EdgeQL schema, and is intended to be used to implement client APIs and integrate into the wider GraphQL ecosystem, but it's not the primary way to interact with data.  For example, we also provide a [simpler REST-based protocol](https://edgedb.com/docs/clients/90_edgeql/protocol) and will likely support more RPC protocols in the future.

Please take a look at our [Roadmap](https://edgedb.com/roadmap/) to learn more about various aspects of EdgeDB (including those in development.)

> How edgedb compares in performance to dgraph? Here is the problem of  multifetching with graph on top of traditional db, in dgraph blog, and they say that problem does not exist with dgraph.

A query of any complexity in EdgeDB is always translated into a single PostgresSQL query, so the "N+1 problem" is not a thing here either. This is true even for queries that do recursive inserts or updates, which ensures atomicity even when explicit transactions are not used.

We do not currently have any benchmarks against Dgraph, and I don't think it would be very meaningful to compare the two, since we optimize for different problems.  That said, if you're interested in the general performance of EdgeDB, we have published benchmarks against popular ORM libraries in [this blog post](https://edgedb.com/blog/edgedb-1-0-alpha-1/).  We will have more soon.

Please feel free to join our [community chat](https://spectrum.chat/edgedb), I'd be happy to answer more questions if you have them.

**Comment by lishine** [comment]
Thank you very much.
Would like to see a performance comparison against Hasura.

**Comment by manishrjain** [comment]
> Dgraph is a graph database, like Neo4j, and is primarily oriented toward working with sparse data that does not have a strictly defined schema.

That's not true. Dgraph runs on schema, but allows flexibility. If one is not provided, it "infers" it. But, then enforces it on all future writes. It also have 2 level of schema -- one at storage, and one user-facing. So, a user-facing schema can be changed on the fly (say, int to datetime), without having to go back and re-write all the data at storage level. All of this makes Dgraph "appear" schema-less, while having a pretty solid schema support.

Dgraph's niche is that it's a graph platform for building applications. So, it's unlike Neo4j, which is more focused on graph analytics and not as a source of truth. It's also unlike Hasura or EdgeDB, which are built as layers on top of Postgres.

Dgraph supports GraphQL natively and its custom QL is a fork of GraphQL. It doesn't have to "translate" any of this to another DB's query language. Because, as a DB written from scratch, it can handle all of this natively.
