### ISSUE TITLE
Client graphql query

### ISSUE THREAD

**Issue by lishine** [edgedb/edgedb#951]
What is the reccommendated way to build application when quering from client with graphql.
Where on the server do I insert the business logic.
Should I build Apollo server and pass queries through it and it's resolvers to Edgedb?

**Comment by elprans** [comment]
> What is the reccommendated way to build application when quering from client with graphql.

The currently recommended approach is to define your GraphQL API in terms of [EdgeQL views](https://edgedb.com/docs/datamodel/views).  [The tutorial](https://edgedb.com/docs/tutorial/graphql/#ref-tutorial-graphql) has a few examples. 

Unlike SQL databases, EdgeDB allows defining views with arbitrarily nested shape. For example:

```
view MovieOverview := (
    SELECT Movie {
        title,
        top_actors := (SELECT .actors {
           name
        } ORDER BY @list_order LIMIT 10),
       
        latest_reviews := (
            SELECT .reviews {
                body,
                rating,
                author: {
                    name,
                    image,
                }
            }
            ORDER BY .creation_time DESC
        ),
    }
)
```

Having defined this view, you can query the it with GraphQL from your client:

```
{
    MovieOverview(
        filter: {title: {eq: "Blade Runner"}}
    ) {
        top_actors {
            name
        },
        latest_reviews {
            body,
            rating,
            author {
                name
            }
        }
    }
}
```

There are great benefits in using views for GraphQL:

1. You expose only the things you want to expose and can transform and reshape the data in any way so that client GraphQL queries stay simple.

2. Your GraphQL API is not tied directly to your database schema, you can always change the underlying structure and modify the existing views to accommodate that.

We are working on features like [advanced access control](https://edgedb.com/roadmap/#access_control) and database views to make defining stable and safe APIs even easier.

>  Should I build Apollo server and pass queries through it and it's resolvers to Edgedb?

It would make sense if you want to write other resolvers for things not in your database.  Data from EdgeDB then becomes part of your overall GraphQL schema.  If your use case is simple enough, then you might find that EdgeDB alone is enough.

**Comment by elprans** [comment]
Feel free to ask more questions in the [community chat](https://spectrum.chat/edgedb).
