### ISSUE TITLE
Update tutorial for Alpha 2

### ISSUE THREAD

**Issue by tailhook** [edgedb/edgedb#974]
At least `module default {}` is missing. But this I've just stumbled upon. Didn't check other things.

Not sure what is a good time though (before or right after a release?)

**Comment by tailhook** [comment]
Hm, I see it in the master but not on site. Do we publish site docs from a branch?

**Comment by 1st1** [comment]
@vpetrovykh could you please take a look at this when you have a minute?

**Comment by vpetrovykh** [comment]
So the code in master should be OK (I've explicitly verified that I could run the tutorial commands in REPL for the current edgedb version). We do actually test the syntax of snippets used in the docs (including SDL in migraitons). Having said that, I need to update the description of SDL in the docs because the way it refers to modules is not accurate anymore. I'll probably overall need to review mentions of "SDL" and "module" in the actual descriptive text rather than in code snippets.
